# frozen_string_literal: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "*.gemspec"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 200

Layout/LineLength:
  Max: 120
