include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - unawaited_futures

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.pb.dart"
    - "**/*.pbenum.dart"
    - "**/*.pbjson.dart"
    - "**/*.pbgrpc.dart"
