-- ============================================================================
-- Flyway Migration V1: Baseline Schema
-- ============================================================================
-- This migration captures the existing schema that was previously managed
-- by Hibernate's hbm2ddl.auto=update. Converting to Flyway ensures:
--   1. Repeatable, version-controlled schema changes
--   2. No more schema drift between environments
--   3. Safe rollback capability
--   4. Audit trail of every schema modification
--
-- Replaces: hibernate.cfg.xml <property name="hibernate.hbm2ddl.auto">update</property>
-- ============================================================================

-- Sequences
CREATE SEQUENCE IF NOT EXISTS POLICY_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS CLAIM_SEQ START WITH 5000 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PAYMENT_SEQ START WITH 10000 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS AUDIT_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS NOTE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SNAPSHOT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ENDORSEMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ADJUSTER_SEQ START WITH 100 INCREMENT BY 1;

-- POLICY
CREATE TABLE IF NOT EXISTS POLICY (
    ID                  BIGINT          NOT NULL,
    VERSION             INTEGER         DEFAULT 0,
    POLICY_NUMBER       VARCHAR(20)     NOT NULL,
    STATUS              VARCHAR(20)     NOT NULL,
    POLICY_TYPE         VARCHAR(30)     NOT NULL,
    HOLDER_FIRST_NAME   VARCHAR(50)     NOT NULL,
    HOLDER_LAST_NAME    VARCHAR(50)     NOT NULL,
    HOLDER_SSN          VARCHAR(11),
    HOLDER_EMAIL        VARCHAR(100),
    HOLDER_PHONE        VARCHAR(20),
    EFFECTIVE_DATE      DATE            NOT NULL,
    EXPIRATION_DATE     DATE            NOT NULL,
    PREMIUM_AMOUNT      DECIMAL(12,2),
    COVERAGE_LIMIT      DECIMAL(14,2),
    DEDUCTIBLE          DECIMAL(10,2),
    AGENT_CODE          VARCHAR(10),
    UNDERWRITER_CODE    VARCHAR(10),
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_POLICY PRIMARY KEY (ID),
    CONSTRAINT UK_POLICY_NUMBER UNIQUE (POLICY_NUMBER)
);

-- CLAIM
CREATE TABLE IF NOT EXISTS CLAIM (
    ID                  BIGINT          NOT NULL,
    VERSION             INTEGER         DEFAULT 0,
    CLAIM_NUMBER        VARCHAR(20)     NOT NULL,
    POLICY_ID           BIGINT          NOT NULL,
    STATUS              VARCHAR(20)     NOT NULL,
    CLAIM_TYPE          VARCHAR(30)     NOT NULL,
    LOSS_DATE           DATE            NOT NULL,
    REPORTED_DATE       TIMESTAMP       NOT NULL,
    LOSS_DESCRIPTION    VARCHAR(2000),
    LOSS_LOCATION       VARCHAR(200),
    CLAIMANT_FIRST_NAME VARCHAR(50)     NOT NULL,
    CLAIMANT_LAST_NAME  VARCHAR(50)     NOT NULL,
    CLAIMANT_PHONE      VARCHAR(50),
    CLAIMANT_EMAIL      VARCHAR(100),
    ADJUSTER_CODE       VARCHAR(10),
    ESTIMATED_LOSS      DECIMAL(14,2),
    APPROVED_AMOUNT     DECIMAL(14,2),
    DEDUCTIBLE_APPLIED  DECIMAL(10,2),
    FRAUD_RISK_LEVEL    VARCHAR(20),
    FRAUD_SCORE         INTEGER,
    FRAUD_SCORED_DATE   TIMESTAMP,
    CLOSED_DATE         TIMESTAMP,
    CLOSED_REASON       VARCHAR(500),
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_CLAIM PRIMARY KEY (ID),
    CONSTRAINT UK_CLAIM_NUMBER UNIQUE (CLAIM_NUMBER),
    CONSTRAINT FK_CLAIM_POLICY FOREIGN KEY (POLICY_ID) REFERENCES POLICY(ID)
);

-- CLAIM_PAYMENT
CREATE TABLE IF NOT EXISTS CLAIM_PAYMENT (
    ID                  BIGINT          NOT NULL,
    VERSION             INTEGER         DEFAULT 0,
    CLAIM_ID            BIGINT          NOT NULL,
    PAYMENT_NUMBER      VARCHAR(20)     NOT NULL,
    PAYMENT_STATUS      VARCHAR(20)     NOT NULL,
    PAYMENT_METHOD      VARCHAR(20),
    AMOUNT              DECIMAL(14,2)   NOT NULL,
    SCHEDULED_DATE      DATE,
    PROCESSED_DATE      TIMESTAMP,
    PAYEE_NAME          VARCHAR(100)    NOT NULL,
    PAYEE_ADDRESS       VARCHAR(200),
    CHECK_NUMBER        VARCHAR(20),
    MEMO                VARCHAR(500),
    APPROVED_BY         VARCHAR(50),
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_PAYMENT PRIMARY KEY (ID),
    CONSTRAINT UK_PAYMENT_NUMBER UNIQUE (PAYMENT_NUMBER),
    CONSTRAINT FK_PAYMENT_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM(ID)
);

-- CLAIM_AUDIT
CREATE TABLE IF NOT EXISTS CLAIM_AUDIT (
    ID                  BIGINT          NOT NULL,
    VERSION             INTEGER         DEFAULT 0,
    CLAIM_ID            BIGINT          NOT NULL,
    EVENT_TIMESTAMP     TIMESTAMP       NOT NULL,
    EVENT_TYPE          VARCHAR(50)     NOT NULL,
    PREVIOUS_VALUE      VARCHAR(500),
    NEW_VALUE           VARCHAR(500),
    PERFORMED_BY        VARCHAR(50)     NOT NULL,
    DESCRIPTION         VARCHAR(1000),
    IP_ADDRESS          VARCHAR(45),
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_AUDIT PRIMARY KEY (ID),
    CONSTRAINT FK_AUDIT_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM(ID)
);

-- CLAIM_NOTE
CREATE TABLE IF NOT EXISTS CLAIM_NOTE (
    ID                  BIGINT          NOT NULL,
    VERSION             INTEGER         DEFAULT 0,
    CLAIM_ID            BIGINT          NOT NULL,
    NOTE_TYPE           VARCHAR(30),
    SUBJECT             VARCHAR(200)    NOT NULL,
    CONTENT             CLOB,
    AUTHOR_NAME         VARCHAR(50)     NOT NULL,
    CONFIDENTIAL        BOOLEAN         DEFAULT FALSE,
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_NOTE PRIMARY KEY (ID),
    CONSTRAINT FK_NOTE_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM(ID)
);

-- CLAIM_SNAPSHOT
CREATE TABLE IF NOT EXISTS CLAIM_SNAPSHOT (
    ID                  BIGINT          NOT NULL,
    VERSION             INTEGER         DEFAULT 0,
    CLAIM_ID            BIGINT          NOT NULL,
    SNAPSHOT_DATE       TIMESTAMP       NOT NULL,
    SNAPSHOT_REASON     VARCHAR(100),
    POLICY_NUMBER       VARCHAR(20),
    CLAIM_NUMBER        VARCHAR(20),
    STATUS              VARCHAR(20),
    CLAIM_TYPE          VARCHAR(30),
    ESTIMATED_LOSS      DECIMAL(14,2),
    APPROVED_AMOUNT     DECIMAL(14,2),
    ADJUSTER_CODE       VARCHAR(10),
    FRAUD_SCORE         INTEGER,
    FRAUD_RISK_LEVEL    VARCHAR(20),
    SERIALIZED_DATA     CLOB,
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_SNAPSHOT PRIMARY KEY (ID)
);

-- POLICY_ENDORSEMENT
CREATE TABLE IF NOT EXISTS POLICY_ENDORSEMENT (
    ID                  BIGINT          NOT NULL,
    VERSION             INTEGER         DEFAULT 0,
    POLICY_ID           BIGINT          NOT NULL,
    ENDORSEMENT_NUMBER  VARCHAR(20),
    ENDORSEMENT_TYPE    VARCHAR(50),
    EFFECTIVE_DATE      DATE,
    PREMIUM_ADJUSTMENT  DECIMAL(12,2),
    DESCRIPTION         VARCHAR(500),
    ACTIVE              BOOLEAN         DEFAULT TRUE,
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_ENDORSEMENT PRIMARY KEY (ID),
    CONSTRAINT FK_ENDORSEMENT_POLICY FOREIGN KEY (POLICY_ID) REFERENCES POLICY(ID)
);

-- ADJUSTER
CREATE TABLE IF NOT EXISTS ADJUSTER (
    ID                  BIGINT          NOT NULL,
    VERSION             INTEGER         DEFAULT 0,
    ADJUSTER_CODE       VARCHAR(10)     NOT NULL,
    FIRST_NAME          VARCHAR(50)     NOT NULL,
    LAST_NAME           VARCHAR(50)     NOT NULL,
    EMAIL               VARCHAR(100),
    PHONE               VARCHAR(20),
    SPECIALIZATION      VARCHAR(50),
    ACTIVE              BOOLEAN         DEFAULT TRUE,
    MAX_CASELOAD        INTEGER         DEFAULT 50,
    CURRENT_CASELOAD    INTEGER         DEFAULT 0,
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_ADJUSTER PRIMARY KEY (ID),
    CONSTRAINT UK_ADJUSTER_CODE UNIQUE (ADJUSTER_CODE)
);
