-- ============================================================================
-- Flyway Migration V2: Add Performance Indexes and Constraints
-- ============================================================================
-- This migration adds indexes identified during production performance tuning.
-- In the legacy system these were applied via ad-hoc DBA scripts; Flyway
-- ensures they are tracked, versioned, and consistently applied everywhere.
-- ============================================================================

-- Policy indexes for common search patterns
CREATE INDEX IF NOT EXISTS IDX_POLICY_STATUS
    ON POLICY (STATUS);
CREATE INDEX IF NOT EXISTS IDX_POLICY_TYPE
    ON POLICY (POLICY_TYPE);
CREATE INDEX IF NOT EXISTS IDX_POLICY_HOLDER_LAST
    ON POLICY (HOLDER_LAST_NAME);
CREATE INDEX IF NOT EXISTS IDX_POLICY_EFFECTIVE
    ON POLICY (EFFECTIVE_DATE);
CREATE INDEX IF NOT EXISTS IDX_POLICY_EXPIRATION
    ON POLICY (EXPIRATION_DATE);
CREATE INDEX IF NOT EXISTS IDX_POLICY_AGENT
    ON POLICY (AGENT_CODE);

-- Claim indexes for dashboard queries and adjuster workqueues
CREATE INDEX IF NOT EXISTS IDX_CLAIM_STATUS
    ON CLAIM (STATUS);
CREATE INDEX IF NOT EXISTS IDX_CLAIM_TYPE
    ON CLAIM (CLAIM_TYPE);
CREATE INDEX IF NOT EXISTS IDX_CLAIM_POLICY
    ON CLAIM (POLICY_ID);
CREATE INDEX IF NOT EXISTS IDX_CLAIM_ADJUSTER
    ON CLAIM (ADJUSTER_CODE);
CREATE INDEX IF NOT EXISTS IDX_CLAIM_LOSS_DATE
    ON CLAIM (LOSS_DATE);
CREATE INDEX IF NOT EXISTS IDX_CLAIM_REPORTED_DATE
    ON CLAIM (REPORTED_DATE);
CREATE INDEX IF NOT EXISTS IDX_CLAIM_FRAUD_RISK
    ON CLAIM (FRAUD_RISK_LEVEL);
CREATE INDEX IF NOT EXISTS IDX_CLAIM_CLOSED_DATE
    ON CLAIM (CLOSED_DATE);

-- Composite index for claim search screen (status + type + date range)
CREATE INDEX IF NOT EXISTS IDX_CLAIM_SEARCH_COMPOSITE
    ON CLAIM (STATUS, CLAIM_TYPE, LOSS_DATE);

-- Composite index for aging job (status + reported date)
CREATE INDEX IF NOT EXISTS IDX_CLAIM_AGING
    ON CLAIM (STATUS, REPORTED_DATE);

-- Payment indexes for payout scheduling and reconciliation
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_CLAIM
    ON CLAIM_PAYMENT (CLAIM_ID);
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_STATUS
    ON CLAIM_PAYMENT (PAYMENT_STATUS);
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_SCHEDULED
    ON CLAIM_PAYMENT (SCHEDULED_DATE);
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_PROCESSED
    ON CLAIM_PAYMENT (PROCESSED_DATE);

-- Composite index for payout scheduling job
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_SCHEDULING
    ON CLAIM_PAYMENT (PAYMENT_STATUS, SCHEDULED_DATE);

-- Audit indexes for compliance reporting
CREATE INDEX IF NOT EXISTS IDX_AUDIT_CLAIM
    ON CLAIM_AUDIT (CLAIM_ID);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_TIMESTAMP
    ON CLAIM_AUDIT (EVENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_TYPE
    ON CLAIM_AUDIT (EVENT_TYPE);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_USER
    ON CLAIM_AUDIT (PERFORMED_BY);

-- Note indexes
CREATE INDEX IF NOT EXISTS IDX_NOTE_CLAIM
    ON CLAIM_NOTE (CLAIM_ID);
CREATE INDEX IF NOT EXISTS IDX_NOTE_CONFIDENTIAL
    ON CLAIM_NOTE (CLAIM_ID, CONFIDENTIAL);

-- Snapshot indexes for point-in-time queries
CREATE INDEX IF NOT EXISTS IDX_SNAPSHOT_CLAIM
    ON CLAIM_SNAPSHOT (CLAIM_ID);
CREATE INDEX IF NOT EXISTS IDX_SNAPSHOT_DATE
    ON CLAIM_SNAPSHOT (SNAPSHOT_DATE);

-- Endorsement indexes
CREATE INDEX IF NOT EXISTS IDX_ENDORSEMENT_POLICY
    ON POLICY_ENDORSEMENT (POLICY_ID);
CREATE INDEX IF NOT EXISTS IDX_ENDORSEMENT_ACTIVE
    ON POLICY_ENDORSEMENT (POLICY_ID, ACTIVE);

-- Adjuster indexes
CREATE INDEX IF NOT EXISTS IDX_ADJUSTER_ACTIVE
    ON ADJUSTER (ACTIVE);
CREATE INDEX IF NOT EXISTS IDX_ADJUSTER_SPECIALIZATION
    ON ADJUSTER (SPECIALIZATION);

-- Add check constraints for data integrity (replacing application-level validation)
ALTER TABLE CLAIM_PAYMENT ADD CONSTRAINT IF NOT EXISTS CHK_PAYMENT_AMOUNT
    CHECK (AMOUNT > 0);
ALTER TABLE POLICY ADD CONSTRAINT IF NOT EXISTS CHK_POLICY_DATES
    CHECK (EXPIRATION_DATE > EFFECTIVE_DATE);
ALTER TABLE POLICY ADD CONSTRAINT IF NOT EXISTS CHK_PREMIUM_POSITIVE
    CHECK (PREMIUM_AMOUNT IS NULL OR PREMIUM_AMOUNT >= 0);
ALTER TABLE CLAIM ADD CONSTRAINT IF NOT EXISTS CHK_LOSS_DATE
    CHECK (LOSS_DATE <= REPORTED_DATE);
