using System;
/*
    IMPORTANT: Most of the code is generated by AI, then modified by me. Review carefully before implementation.
    Though I have tested it, and the parts I tested work, there may be bugs and/or runtime errors.
    IMPORTANT: This program is made by an indie developer. The program is not sponsored by, nor represents major tech firms
    like Microsoft, Google, Amazon, Apple, etc.

    LANGUAGE VERSION: C# 8.0+

    WARNING: This program contains over 1300 lines of code; modifying it may require a group effort.

    NOTE: This program is purely for educational purposes, not meant as a professional solution to XYZ problem.

    This is a simple unit converter program.
    It converts between different units of measurement.

    To run this program,
    1. Install the C# Dev Kit on your Visual Studio Code IDE.
    2. And then run the program in Visual Studios
*/
namespace unit_converter
{
  class Program
  {
        //Unit conversion functions
        //Length conversions
        public static double MetersToFeet(double meters) => meters * 3.28084;
        public static double FeetToMeters(double feet) => feet / 3.28084;
        public static double KilometersToMiles(double kilometers) => kilometers * 0.621371;
        public static double MilesToKilometers(double miles) => miles / 0.621371;
        public static double CentimetersToInches(double centimeters) => centimeters * 0.393701;
        public static double InchesToCentimeters(double inches) => inches / 0.393701;
        //Weight conversions
        public static double KilogramsToPounds(double kilograms) => kilograms * 2.20462;
        public static double PoundsToKilograms(double pounds) => pounds / 2.20462;
        public static double GramsToOunces(double grams) => grams * 0.035274;
        public static double OuncesToGrams(double ounces) => ounces / 0.035274;
        //Temperature conversions
        public static double CelsiusToFahrenheit(double celsius) => (celsius * 9 / 5) + 32;
        public static double FahrenheitToCelsius(double fahrenheit) => (fahrenheit - 32) * 5 / 9;
        public static double CelsiusToKelvin(double celsius) => celsius + 273.15;
        public static double KelvinToCelsius(double kelvin) => kelvin - 273.15;
        public static double FahrenheitToKelvin(double fahrenheit) => (fahrenheit - 32) * 5 / 9 + 273.15;
        public static double KelvinToFahrenheit(double kelvin) => (kelvin - 273.15) * 9 / 5 + 32;
        //Volume conversions
        public static double LitersToGallons(double liters) => liters * 0.264172;
        public static double GallonsToLiters(double gallons) => gallons / 0.264172;
        public static double MillilitersToFluidOunces(double milliliters) => milliliters * 0.033814;
        public static double FluidOuncesToMilliliters(double fluidOunces) => fluidOunces / 0.033814;
        public static double CubicMetersToCubicFeet(double cubicMeters) => cubicMeters * 35.3147;
        public static double CubicFeetToCubicMeters(double cubicFeet) => cubicFeet / 35.3147;
        //Area conversions
        public static double SquareMetersToSquareFeet(double squareMeters) => squareMeters * 10.7639;
        public static double SquareFeetToSquareMeters(double squareFeet) => squareFeet / 10.7639;
        public static double HectaresToAcres(double hectares) => hectares * 2.47105;
        public static double AcresToHectares(double acres) => acres / 2.47105;
        public static double SquareKilometersToSquareMiles(double squareKilometers) => squareKilometers * 0.386102;
        public static double SquareMilesToSquareKilometers(double squareMiles) => squareMiles / 0.386102;
        //Speed conversions
        public static double KilometersPerHourToMilesPerHour(double kmh) => kmh * 0.621371;
        public static double MilesPerHourToKilometersPerHour(double mph) => mph / 0.621371;
        public static double MetersPerSecondToFeetPerSecond(double mps) => mps * 3.28084;
        public static double FeetPerSecondToMetersPerSecond(double fps) => fps / 3.28084;
        public static double KnotsToMilesPerHour(double knots) => knots * 1.15078;
        public static double MilesPerHourToKnots(double mph) => mph / 1.15078;
        //Time conversions
        public static double SecondsToMinutes(double seconds) => seconds / 60;
        public static double MinutesToSeconds(double minutes) => minutes * 60;
        public static double MinutesToHours(double minutes) => minutes / 60;
        public static double HoursToMinutes(double hours) => hours * 60;
        public static double HoursToDays(double hours) => hours / 24;
        public static double DaysToHours(double days) => days * 24;
        public static double DaysToWeeks(double days) => days / 7;
        public static double WeeksToDays(double weeks) => weeks * 7;
        public static double WeeksToMonths(double weeks) => weeks / 4.34524;
        public static double MonthsToWeeks(double months) => months * 4.34524;
        public static double MonthsToYears(double months) => months / 12;
        public static double YearsToMonths(double years) => years * 12;
        //Data storage conversions
        public static double BytesToKilobytes(double bytes) => bytes / 1024;
        public static double KilobytesToBytes(double kilobytes) => kilobytes * 1024;
        public static double KilobytesToMegabytes(double kilobytes) => kilobytes / 1024;
        public static double MegabytesToKilobytes(double megabytes) => megabytes * 1024;
        public static double MegabytesToGigabytes(double megabytes) => megabytes / 1024;
        public static double GigabytesToMegabytes(double gigabytes) => gigabytes * 1024;
        public static double GigabytesToTerabytes(double gigabytes) => gigabytes / 1024;
        public static double TerabytesToGigabytes(double terabytes) => terabytes * 1024;
        //Energy conversions
        public static double JoulesToCalories(double joules) => joules * 0.239006;
        public static double CaloriesToJoules(double calories) => calories / 0.239006;
        public static double KilojoulesToKilocalories(double kilojoules) => kilojoules * 0.239006;
        public static double KilocaloriesToKilojoules(double kilocalories) => kilocalories / 0.239006;
        public static double WattHoursToKilowattHours(double wattHours) => wattHours / 1000;
        public static double KilowattHoursToWattHours(double kilowattHours) => kilowattHours * 1000;
        public static double ElectronvoltsToJoules(double electronvolts) => electronvolts * 1.60218e-19;
        public static double JoulesToElectronvolts(double joules) => joules / 1.60218e-19;
        //Pressure conversions
        public static double PascalsToAtmospheres(double pascals) => pascals / 101325;
        public static double AtmospheresToPascals(double atmospheres) => atmospheres * 101325;
        public static double BarsToPascals(double bars) => bars * 100000;
        public static double PascalsToBars(double pascals) => pascals / 100000;
        public static double PSIToPascals(double psi) => psi * 6894.76;
        public static double PascalsToPSI(double pascals) => pascals / 6894.76;
        //Frequency conversions
        public static double HertzToKilohertz(double hertz) => hertz / 1000;
        public static double KilohertzToHertz(double kilohertz) => kilohertz * 1000;
        public static double KilohertzToMegahertz(double kilohertz) => kilohertz / 1000;
        public static double MegahertzToKilohertz(double megahertz) => megahertz * 1000;
        public static double MegahertzToGigahertz(double megahertz) => megahertz / 1000;
        public static double GigahertzToMegahertz(double gigahertz) => gigahertz * 1000;
        //Angle conversions
        public static double DegreesToRadians(double degrees) => degrees * (Math.PI / 180);
        public static double RadiansToDegrees(double radians) => radians * (180 / Math.PI);
        public static double DegreesToGradians(double degrees) => degrees * (200 / 180);
        public static double GradiansToDegrees(double gradians) => gradians * (180 / 200);
        public static double RadiansToGradians(double radians) => radians * (200 / Math.PI);
        public static double GradiansToRadians(double gradians) => gradians * (Math.PI / 200);
        //velocity conversions
        public static double MetersPerSecondToKilometersPerSecond(double mps) => mps / 1000;
        public static double KilometersPerSecondToMetersPerSecond(double kmps) => kmps * 1000;
        public static double KilometersPerSecondToMilesPerSecond(double kmps) => kmps * 0.621371;
        public static double MilesPerSecondToKilometersPerSecond(double mps) => mps / 0.621371;
        public static double MilesPerSecondToMilesPerHour(double mps) => mps * 3600;
        public static double MilesPerHourToMilesPerSecond(double mph) => mph / 3600;
        public static double KilometersPerHourToMetersPerSecond(double kmh) => kmh / 3.6;
        public static double MetersPerSecondToKilometersPerHour(double mps) => mps * 3.6;
        //Density conversions
        public static double KilogramsPerCubicMeterToGramsPerCubicCentimeter(double kgm3) => kgm3 / 1000;
        public static double GramsPerCubicCentimeterToKilogramsPerCubicMeter(double gcm3) => gcm3 * 1000;
        public static double PoundsPerCubicFootToKilogramsPerCubicMeter(double pcf) => pcf * 16.0185;
        public static double KilogramsPerCubicMeterToPoundsPerCubicFoot(double kgm3) => kgm3 / 16.0185;
        public static double PoundsPerCubicInchToGramsPerCubicCentimeter(double pci) => pci * 27.6799;
        public static double GramsPerCubicCentimeterToPoundsPerCubicInch(double gcm3) => gcm3 / 27.6799;
        //Power conversions
        public static double WattsToHorsepower(double watts) => watts / 745.7;
        public static double HorsepowerToWatts(double horsepower) => horsepower * 745.7;
        public static double KilowattsToHorsepower(double kilowatts) => kilowatts * 1.34102;
        public static double HorsepowerToKilowatts(double horsepower) => horsepower / 1.34102;
        public static double MegawattsToHorsepower(double megawatts) => megawatts * 1341.02;
        public static double HorsepowerToMegawatts(double horsepower) => horsepower / 1341.02;
        //Main method
        static void Main(string[] args)
        {
            Console.WriteLine("======== Simple Unit Converter ========");
            Console.WriteLine("This program provides various unit conversion functions.");
            Console.WriteLine("You can call the conversion functions directly from the code.");
            Console.WriteLine("The following commands convert values between different units:");
            Console.WriteLine("The syntax is: <FunctionName>, and then (<value>)");
            Console.WriteLine("For example: MetersToFeet(10) converts 10 meters to feet.");
            Console.WriteLine("=======================================");
            Console.WriteLine("Commands available:");
            Console.WriteLine("Length: MetersToFeet, FeetToMeters, KilometersToMiles, MilesToKilometers, CentimetersToInches, InchesToCentimeters");
            Console.WriteLine("Weight: KilogramsToPounds, PoundsToKilograms, GramsToOunces, OuncesToGrams");
            Console.WriteLine("Temperature: CelsiusToFahrenheit, FahrenheitToCelsius, CelsiusToKelvin, KelvinToCelsius, FahrenheitToKelvin, KelvinToFahrenheit");
            Console.WriteLine("Volume: LitersToGallons, GallonsToLiters, MillilitersToFluidOunces, FluidOuncesToMilliliters, CubicMetersToCubicFeet, CubicFeetToCubicMeters");
            Console.WriteLine("Area: SquareMetersToSquareFeet, SquareFeetToSquareMeters, HectaresToAcres, AcresToHectares, SquareKilometersToSquareMiles, SquareMilesToSquareKilometers");
            Console.WriteLine("Speed: KilometersPerHourToMilesPerHour, MilesPerHourToKilometersPerHour, MetersPerSecondToFeetPerSecond, FeetPerSecondToMetersPerSecond, KnotsToMilesPerHour, MilesPerHourToKnots");
            Console.WriteLine("Time: SecondsToMinutes, MinutesToSeconds, MinutesToHours, HoursToMinutes, HoursToDays, DaysToHours, DaysToWeeks, WeeksToDays, WeeksToMonths, MonthsToWeeks, MonthsToYears, YearsToMonths");
            Console.WriteLine("Data Storage: BytesToKilobytes, KilobytesToBytes, KilobytesToMegabytes, MegabytesToKilobytes, MegabytesToGigabytes, GigabytesToMegabytes, GigabytesToTerabytes, TerabytesToGigabytes");
            Console.WriteLine("Energy: JoulesToCalories, CaloriesToJoules, KilojoulesToKilocalories, KilocaloriesToKilojoules, WattHoursToKilowattHours, KilowattHoursToWattHours, ElectronvoltsToJoules, JoulesToElectronvolts");
            Console.WriteLine("Pressure: PascalsToAtmospheres, AtmospheresToPascals, BarsToPascals, PascalsToBars, PSIToPascals, PascalsToPSI");
            Console.WriteLine("Frequency: HertzToKilohertz, KilohertzToHertz, KilohertzToMegahertz, MegahertzToKilohertz, MegahertzToGigahertz, GigahertzToMegahertz");
            Console.WriteLine("Angle: DegreesToRadians, RadiansToDegrees, DegreesToGradians, GradiansToDegrees, RadiansToGradians, GradiansToRadians");
            Console.WriteLine("Velocity: MetersPerSecondToKilometersPerSecond, KilometersPerSecondToMetersPerSecond, KilometersPerSecondToMilesPerSecond, MilesPerSecondToKilometersPerSecond, MilesPerSecondToMilesPerHour, MilesPerHourToMilesPerSecond, KilometersPerHourToMetersPerSecond, MetersPerSecondToKilometersPerHour");
            Console.WriteLine("Density: KilogramsPerCubicMeterToGramsPerCubicCentimeter, GramsPerCubicCentimeterToKilogramsPerCubicMeter, PoundsPerCubicFootToKilogramsPerCubicMeter, KilogramsPerCubicMeterToPoundsPerCubicFoot, PoundsPerCubicInchToGramsPerCubicCentimeter, GramsPerCubicCentimeterToPoundsPerCubicInch");
            Console.WriteLine("Power: WattsToHorsepower, HorsepowerToWatts, KilowattsToHorsepower, HorsepowerToKilowatts, MegawattsToHorsepower, HorsepowerToMegawatts");
            Console.WriteLine("=======================================");
            while (true)
            {
                Console.WriteLine("Enter a command (or type 'exit' to quit):");
                string input = Console.ReadLine();
                if (input.ToLower() == "exit")
                {
                    break;
                }
                else if (input.ToLower() == "meterstofeet")
                {
                    Console.WriteLine("Enter value in meters:");
                    if (double.TryParse(Console.ReadLine(), out double meters))
                    {
                        double feet = MetersToFeet(meters);
                        Console.WriteLine($"{meters} meters is {feet} feet.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "feettometers")
                {
                    Console.WriteLine("Enter value in feet:");
                    if (double.TryParse(Console.ReadLine(), out double feet))
                    {
                        double meters = FeetToMeters(feet);
                        Console.WriteLine($"{feet} feet is {meters} meters.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "kilometerstomiles")
                {
                    Console.WriteLine("Enter value in kilometers:");
                    if (double.TryParse(Console.ReadLine(), out double kilometers))
                    {
                        double miles = KilometersToMiles(kilometers);
                        Console.WriteLine($"{kilometers} kilometers is {miles} miles.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "milestokilometers")
                {
                    Console.WriteLine("Enter value in miles:");
                    if (double.TryParse(Console.ReadLine(), out double miles))
                    {
                        double kilometers = MilesToKilometers(miles);
                        Console.WriteLine($"{miles} miles is {kilometers} kilometers.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "centimeterstoinches")
                {
                    Console.WriteLine("Enter value in centimeters:");
                    if (double.TryParse(Console.ReadLine(), out double centimeters))
                    {
                        double inches = CentimetersToInches(centimeters);
                        Console.WriteLine($"{centimeters} centimeters is {inches} inches.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "inchestocentimeters")
                {
                    Console.WriteLine("Enter value in inches:");
                    if (double.TryParse(Console.ReadLine(), out double inches))
                    {
                        double centimeters = InchesToCentimeters(inches);
                        Console.WriteLine($"{inches} inches is {centimeters} centimeters.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "kilogramstopounds")
                {
                    Console.WriteLine("Enter value in kilograms:");
                    if (double.TryParse(Console.ReadLine(), out double kilograms))
                    {
                        double pounds = KilogramsToPounds(kilograms);
                        Console.WriteLine($"{kilograms} kilograms is {pounds} pounds.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "poundstokilograms")
                {
                    Console.WriteLine("Enter value in pounds:");
                    if (double.TryParse(Console.ReadLine(), out double pounds))
                    {
                        double kilograms = PoundsToKilograms(pounds);
                        Console.WriteLine($"{pounds} pounds is {kilograms} kilograms.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "gramstoounces")
                {
                    Console.WriteLine("Enter value in grams:");
                    if (double.TryParse(Console.ReadLine(), out double grams))
                    {
                        double ounces = GramsToOunces(grams);
                        Console.WriteLine($"{grams} grams is {ounces} ounces.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "ouncestograms")
                {
                    Console.WriteLine("Enter value in ounces:");
                    if (double.TryParse(Console.ReadLine(), out double ounces))
                    {
                        double grams = OuncesToGrams(ounces);
                        Console.WriteLine($"{ounces} ounces is {grams} grams.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "celsiustofahrenheit")
                {
                    Console.WriteLine("Enter value in Celsius:");
                    if (double.TryParse(Console.ReadLine(), out double celsius))
                    {
                        double fahrenheit = CelsiusToFahrenheit(celsius);
                        Console.WriteLine($"{celsius}°C is {fahrenheit}°F.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "fahrenheittocelsius")
                {
                    Console.WriteLine("Enter value in Fahrenheit:");
                    if (double.TryParse(Console.ReadLine(), out double fahrenheit))
                    {
                        double celsius = FahrenheitToCelsius(fahrenheit);
                        Console.WriteLine($"{fahrenheit}°F is {celsius}°C.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "celsiustokelvin")
                {
                    Console.WriteLine("Enter value in Celsius:");
                    if (double.TryParse(Console.ReadLine(), out double celsius))
                    {
                        double kelvin = CelsiusToKelvin(celsius);
                        Console.WriteLine($"{celsius}°C is {kelvin}K.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "kelvintocelsius")
                {
                    Console.WriteLine("Enter value in Kelvin:");
                    if (double.TryParse(Console.ReadLine(), out double kelvin))
                    {
                        double celsius = KelvinToCelsius(kelvin);
                        Console.WriteLine($"{kelvin}K is {celsius}°C.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "fahrenheittokelvin")
                {
                    Console.WriteLine("Enter value in Fahrenheit:");
                    if (double.TryParse(Console.ReadLine(), out double fahrenheit))
                    {
                        double kelvin = FahrenheitToKelvin(fahrenheit);
                        Console.WriteLine($"{fahrenheit}°F is {kelvin}K.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "kelvintofahrenheit")
                {
                    Console.WriteLine("Enter value in Kelvin:");
                    if (double.TryParse(Console.ReadLine(), out double kelvin))
                    {
                        double fahrenheit = KelvinToFahrenheit(kelvin);
                        Console.WriteLine($"{kelvin}K is {fahrenheit}°F.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "litertogallons")
                {
                    Console.WriteLine("Enter value in liters:");
                    if (double.TryParse(Console.ReadLine(), out double liters))
                    {
                        double gallons = LitersToGallons(liters);
                        Console.WriteLine($"{liters} liters is {gallons} gallons.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "gallonstoliters")
                {
                    Console.WriteLine("Enter value in gallons:");
                    if (double.TryParse(Console.ReadLine(), out double gallons))
                    {
                        double liters = GallonsToLiters(gallons);
                        Console.WriteLine($"{gallons} gallons is {liters} liters.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "milliliterstofluidounces")
                {
                    Console.WriteLine("Enter value in milliliters:");
                    if (double.TryParse(Console.ReadLine(), out double milliliters))
                    {
                        double fluidOunces = MillilitersToFluidOunces(milliliters);
                        Console.WriteLine($"{milliliters} milliliters is {fluidOunces} fluid ounces.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "fluidouncestomilliliters")
                {
                    Console.WriteLine("Enter value in fluid ounces:");
                    if (double.TryParse(Console.ReadLine(), out double fluidOunces))
                    {
                        double milliliters = FluidOuncesToMilliliters(fluidOunces);
                        Console.WriteLine($"{fluidOunces} fluid ounces is {milliliters} milliliters.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "cubicmeterstocubicfeet")
                {
                    Console.WriteLine("Enter value in cubic meters:");
                    if (double.TryParse(Console.ReadLine(), out double cubicMeters))
                    {
                        double cubicFeet = CubicMetersToCubicFeet(cubicMeters);
                        Console.WriteLine($"{cubicMeters} cubic meters is {cubicFeet} cubic feet.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "cubicfeettocubicmeters")
                {
                    Console.WriteLine("Enter value in cubic feet:");
                    if (double.TryParse(Console.ReadLine(), out double cubicFeet))
                    {
                        double cubicMeters = CubicFeetToCubicMeters(cubicFeet);
                        Console.WriteLine($"{cubicFeet} cubic feet is {cubicMeters} cubic meters.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "squaremeterstosquarefeet")
                {
                    Console.WriteLine("Enter value in square meters:");
                    if (double.TryParse(Console.ReadLine(), out double squareMeters))
                    {
                        double squareFeet = SquareMetersToSquareFeet(squareMeters);
                        Console.WriteLine($"{squareMeters} square meters is {squareFeet} square feet.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "squarefeettosquaremeters")
                {
                    Console.WriteLine("Enter value in square feet:");
                    if (double.TryParse(Console.ReadLine(), out double squareFeet))
                    {
                        double squareMeters = SquareFeetToSquareMeters(squareFeet);
                        Console.WriteLine($"{squareFeet} square feet is {squareMeters} square meters.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "hectarestoacres")
                {
                    Console.WriteLine("Enter value in hectares:");
                    if (double.TryParse(Console.ReadLine(), out double hectares))
                    {
                        double acres = HectaresToAcres(hectares);
                        Console.WriteLine($"{hectares} hectares is {acres} acres.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "acrestohectares")
                {
                    Console.WriteLine("Enter value in acres:");
                    if (double.TryParse(Console.ReadLine(), out double acres))
                    {
                        double hectares = AcresToHectares(acres);
                        Console.WriteLine($"{acres} acres is {hectares} hectares.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "squarekilometerstosquaremiles")
                {
                    Console.WriteLine("Enter value in square kilometers:");
                    if (double.TryParse(Console.ReadLine(), out double squareKilometers))
                    {
                        double squareMiles = SquareKilometersToSquareMiles(squareKilometers);
                        Console.WriteLine($"{squareKilometers} square kilometers is {squareMiles} square miles.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "squaremilestosquarekilometers")
                {
                    Console.WriteLine("Enter value in square miles:");
                    if (double.TryParse(Console.ReadLine(), out double squareMiles))
                    {
                        double squareKilometers = SquareMilesToSquareKilometers(squareMiles);
                        Console.WriteLine($"{squareMiles} square miles is {squareKilometers} square kilometers.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "kilometersperhourtomilesperhour")
                {
                    Console.WriteLine("Enter value in kilometers per hour:");
                    if (double.TryParse(Console.ReadLine(), out double kmh))
                    {
                        double mph = KilometersPerHourToMilesPerHour(kmh);
                        Console.WriteLine($"{kmh} km/h is {mph} mph.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "milesperhourtokilometersperhour")
                {
                    Console.WriteLine("Enter value in miles per hour:");
                    if (double.TryParse(Console.ReadLine(), out double mph))
                    {
                        double kmh = MilesPerHourToKilometersPerHour(mph);
                        Console.WriteLine($"{mph} mph is {kmh} km/h.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "meterspersecondtofeetpersecond")
                {
                    Console.WriteLine("Enter value in meters per second:");
                    if (double.TryParse(Console.ReadLine(), out double mps))
                    {
                        double fps = MetersPerSecondToFeetPerSecond(mps);
                        Console.WriteLine($"{mps} m/s is {fps} ft/s.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "feetpersecondtometerspersecond")
                {
                    Console.WriteLine("Enter value in feet per second:");
                    if (double.TryParse(Console.ReadLine(), out double fps))
                    {
                        double mps = FeetPerSecondToMetersPerSecond(fps);
                        Console.WriteLine($"{fps} ft/s is {mps} m/s.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "knotstomilesperhour")
                {
                    Console.WriteLine("Enter value in knots:");
                    if (double.TryParse(Console.ReadLine(), out double knots))
                    {
                        double mph = KnotsToMilesPerHour(knots);
                        Console.WriteLine($"{knots} knots is {mph} mph.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "milesperhourtoknots")
                {
                    Console.WriteLine("Enter value in miles per hour:");
                    if (double.TryParse(Console.ReadLine(), out double mph))
                    {
                        double knots = MilesPerHourToKnots(mph);
                        Console.WriteLine($"{mph} mph is {knots} knots.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "secondstominutes")
                {
                    Console.WriteLine("Enter value in seconds:");
                    if (double.TryParse(Console.ReadLine(), out double seconds))
                    {
                        double minutes = SecondsToMinutes(seconds);
                        Console.WriteLine($"{seconds} seconds is {minutes} minutes.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "minutestoseconds")
                {
                    Console.WriteLine("Enter value in minutes:");
                    if (double.TryParse(Console.ReadLine(), out double minutes))
                    {
                        double seconds = MinutesToSeconds(minutes);
                        Console.WriteLine($"{minutes} minutes is {seconds} seconds.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "minutestohours")
                {
                    Console.WriteLine("Enter value in minutes:");
                    if (double.TryParse(Console.ReadLine(), out double minutes))
                    {
                        double hours = MinutesToHours(minutes);
                        Console.WriteLine($"{minutes} minutes is {hours} hours.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "hourstominutes")
                {
                    Console.WriteLine("Enter value in hours:");
                    if (double.TryParse(Console.ReadLine(), out double hours))
                    {
                        double minutes = HoursToMinutes(hours);
                        Console.WriteLine($"{hours} hours is {minutes} minutes.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "hourstodays")
                {
                    Console.WriteLine("Enter value in hours:");
                    if (double.TryParse(Console.ReadLine(), out double hours))
                    {
                        double days = HoursToDays(hours);
                        Console.WriteLine($"{hours} hours is {days} days.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "daystohours")
                {
                    Console.WriteLine("Enter value in days:");
                    if (double.TryParse(Console.ReadLine(), out double days))
                    {
                        double hours = DaysToHours(days);
                        Console.WriteLine($"{days} days is {hours} hours.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "daystoweeks")
                {
                    Console.WriteLine("Enter value in days:");
                    if (double.TryParse(Console.ReadLine(), out double days))
                    {
                        double weeks = DaysToWeeks(days);
                        Console.WriteLine($"{days} days is {weeks} weeks.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "weekstodays")
                {
                    Console.WriteLine("Enter value in weeks:");
                    if (double.TryParse(Console.ReadLine(), out double weeks))
                    {
                        double days = WeeksToDays(weeks);
                        Console.WriteLine($"{weeks} weeks is {days} days.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "weekstomonths")
                {
                    Console.WriteLine("Enter value in weeks:");
                    if (double.TryParse(Console.ReadLine(), out double weeks))
                    {
                        double months = WeeksToMonths(weeks);
                        Console.WriteLine($"{weeks} weeks is {months} months.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "monthstoweeks")
                {
                    Console.WriteLine("Enter value in months:");
                    if (double.TryParse(Console.ReadLine(), out double months))
                    {
                        double weeks = MonthsToWeeks(months);
                        Console.WriteLine($"{months} months is {weeks} weeks.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "monthstoyears")
                {
                    Console.WriteLine("Enter value in months:");
                    if (double.TryParse(Console.ReadLine(), out double months))
                    {
                        double years = MonthsToYears(months);
                        Console.WriteLine($"{months} months is {years} years.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "yearstomonths")
                {
                    Console.WriteLine("Enter value in years:");
                    if (double.TryParse(Console.ReadLine(), out double years))
                    {
                        double months = YearsToMonths(years);
                        Console.WriteLine($"{years} years is {months} months.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "bytestokilobytes")
                {
                    Console.WriteLine("Enter value in bytes:");
                    if (double.TryParse(Console.ReadLine(), out double bytes))
                    {
                        double kilobytes = BytesToKilobytes(bytes);
                        Console.WriteLine($"{bytes} bytes is {kilobytes} kilobytes.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "kilobytetobytes")
                {
                    Console.WriteLine("Enter value in kilobytes:");
                    if (double.TryParse(Console.ReadLine(), out double kilobytes))
                    {
                        double bytes = KilobytesToBytes(kilobytes);
                        Console.WriteLine($"{kilobytes} kilobytes is {bytes} bytes.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "kilobytetomegabytes")
                {
                    Console.WriteLine("Enter value in kilobytes:");
                    if (double.TryParse(Console.ReadLine(), out double kilobytes))
                    {
                        double megabytes = KilobytesToMegabytes(kilobytes);
                        Console.WriteLine($"{kilobytes} kilobytes is {megabytes} megabytes.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "megabytetokilobytes")
                {
                    Console.WriteLine("Enter value in megabytes:");
                    if (double.TryParse(Console.ReadLine(), out double megabytes))
                    {
                        double kilobytes = MegabytesToKilobytes(megabytes);
                        Console.WriteLine($"{megabytes} megabytes is {kilobytes} kilobytes.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "megabytetogigabytes")
                {
                    Console.WriteLine("Enter value in megabytes:");
                    if (double.TryParse(Console.ReadLine(), out double megabytes))
                    {
                        double gigabytes = MegabytesToGigabytes(megabytes);
                        Console.WriteLine($"{megabytes} megabytes is {gigabytes} gigabytes.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "gigabytetomegabytes")
                {
                    Console.WriteLine("Enter value in gigabytes:");
                    if (double.TryParse(Console.ReadLine(), out double gigabytes))
                    {
                        double megabytes = GigabytesToMegabytes(gigabytes);
                        Console.WriteLine($"{gigabytes} gigabytes is {megabytes} megabytes.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "gigabytetoterabytes")
                {
                    Console.WriteLine("Enter value in gigabytes:");
                    if (double.TryParse(Console.ReadLine(), out double gigabytes))
                    {
                        double terabytes = GigabytesToTerabytes(gigabytes);
                        Console.WriteLine($"{gigabytes} gigabytes is {terabytes} terabytes.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "terabytetogigabytes")
                {
                    Console.WriteLine("Enter value in terabytes:");
                    if (double.TryParse(Console.ReadLine(), out double terabytes))
                    {
                        double gigabytes = TerabytesToGigabytes(terabytes);
                        Console.WriteLine($"{terabytes} terabytes is {gigabytes} gigabytes.");
                    }
                    else
                    {
                        Console.WriteLine("Invalid input. Please enter a numeric value.");
                    }
                }
                else if (input.ToLower() == "joulestocalories")
                {
                    Console.WriteLine("Enter value in joules:");
                    if (double.TryParse(Console.ReadLine(), out double joules))
                    {
                        double calories = JoulesToCalories(joules);
                        Console.WriteLine($"{joules} joules is {calories} calories.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "caloriestojoules")
                {
                    Console.WriteLine("Enter value in calories:");
                    if (double.TryParse(Console.ReadLine(), out double calories))
                    {
                        double joules = CaloriesToJoules(calories);
                        Console.WriteLine($"{calories} calories is {joules} joules.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "kilojoulestokilocalories")
                {
                    Console.WriteLine("Enter value in kilojoules:");
                    if (double.TryParse(Console.ReadLine(), out double kj))
                    {
                        double kcal = KilojoulesToKilocalories(kj);
                        Console.WriteLine($"{kj} kilojoules is {kcal} kilocalories.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "kilocaloriestokilojoules")
                {
                    Console.WriteLine("Enter value in kilocalories:");
                    if (double.TryParse(Console.ReadLine(), out double kcal))
                    {
                        double kj = KilocaloriesToKilojoules(kcal);
                        Console.WriteLine($"{kcal} kilocalories is {kj} kilojoules.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "watthourstokilowatthours")
                {
                    Console.WriteLine("Enter value in watt-hours:");
                    if (double.TryParse(Console.ReadLine(), out double wh))
                    {
                        double kwh = WattHoursToKilowattHours(wh);
                        Console.WriteLine($"{wh} watt-hours is {kwh} kilowatt-hours.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "kilowatthourstowattHours")
                {
                    Console.WriteLine("Enter value in kilowatt-hours:");
                    if (double.TryParse(Console.ReadLine(), out double kwh))
                    {
                        double wh = KilowattHoursToWattHours(kwh);
                        Console.WriteLine($"{kwh} kilowatt-hours is {wh} watt-hours.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "electronvoltstojoules")
                {
                    Console.WriteLine("Enter value in electronvolts:");
                    if (double.TryParse(Console.ReadLine(), out double ev))
                    {
                        double joules = ElectronvoltsToJoules(ev);
                        Console.WriteLine($"{ev} eV is {joules} joules.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "joulestoelectronvolts")
                {
                    Console.WriteLine("Enter value in joules:");
                    if (double.TryParse(Console.ReadLine(), out double joules))
                    {
                        double ev = JoulesToElectronvolts(joules);
                        Console.WriteLine($"{joules} joules is {ev} eV.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "pascalstoatmospheres")
                {
                    Console.WriteLine("Enter value in pascals:");
                    if (double.TryParse(Console.ReadLine(), out double pa))
                    {
                        double atm = PascalsToAtmospheres(pa);
                        Console.WriteLine($"{pa} pascals is {atm} atmospheres.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "atmospherestopascals")
                {
                    Console.WriteLine("Enter value in atmospheres:");
                    if (double.TryParse(Console.ReadLine(), out double atm))
                    {
                        double pa = AtmospheresToPascals(atm);
                        Console.WriteLine($"{atm} atmospheres is {pa} pascals.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "barstopascals")
                {
                    Console.WriteLine("Enter value in bars:");
                    if (double.TryParse(Console.ReadLine(), out double bar))
                    {
                        double pa = BarsToPascals(bar);
                        Console.WriteLine($"{bar} bars is {pa} pascals.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "pascalstobars")
                {
                    Console.WriteLine("Enter value in pascals:");
                    if (double.TryParse(Console.ReadLine(), out double pa))
                    {
                        double bar = PascalsToBars(pa);
                        Console.WriteLine($"{pa} pascals is {bar} bars.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "psitopascals")
                {
                    Console.WriteLine("Enter value in PSI:");
                    if (double.TryParse(Console.ReadLine(), out double psi))
                    {
                        double pa = PSIToPascals(psi);
                        Console.WriteLine($"{psi} PSI is {pa} pascals.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "pascalstopsi")
                {
                    Console.WriteLine("Enter value in pascals:");
                    if (double.TryParse(Console.ReadLine(), out double pa))
                    {
                        double psi = PascalsToPSI(pa);
                        Console.WriteLine($"{pa} pascals is {psi} PSI.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "hertztokilohertz")
                {
                    Console.WriteLine("Enter value in hertz:");
                    if (double.TryParse(Console.ReadLine(), out double hz))
                    {
                        double khz = HertzToKilohertz(hz);
                        Console.WriteLine($"{hz} hertz is {khz} kilohertz.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "kilohertztohertz")
                {
                    Console.WriteLine("Enter value in kilohertz:");
                    if (double.TryParse(Console.ReadLine(), out double khz))
                    {
                        double hz = KilohertzToHertz(khz);
                        Console.WriteLine($"{khz} kilohertz is {hz} hertz.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "kilohertztomegahertz")
                {
                    Console.WriteLine("Enter value in kilohertz:");
                    if (double.TryParse(Console.ReadLine(), out double khz))
                    {
                        double mhz = KilohertzToMegahertz(khz);
                        Console.WriteLine($"{khz} kilohertz is {mhz} megahertz.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "megahertztokilohertz")
                {
                    Console.WriteLine("Enter value in megahertz:");
                    if (double.TryParse(Console.ReadLine(), out double mhz))
                    {
                        double khz = MegahertzToKilohertz(mhz);
                        Console.WriteLine($"{mhz} megahertz is {khz} kilohertz.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "megahertztogigahertz")
                {
                    Console.WriteLine("Enter value in megahertz:");
                    if (double.TryParse(Console.ReadLine(), out double mhz))
                    {
                        double ghz = MegahertzToGigahertz(mhz);
                        Console.WriteLine($"{mhz} megahertz is {ghz} gigahertz.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "gigahertztomegahertz")
                {
                    Console.WriteLine("Enter value in gigahertz:");
                    if (double.TryParse(Console.ReadLine(), out double ghz))
                    {
                        double mhz = GigahertzToMegahertz(ghz);
                        Console.WriteLine($"{ghz} gigahertz is {mhz} megahertz.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "degreestoradians")
                {
                    Console.WriteLine("Enter value in degrees:");
                    if (double.TryParse(Console.ReadLine(), out double deg))
                    {
                        double rad = DegreesToRadians(deg);
                        Console.WriteLine($"{deg} degrees is {rad} radians.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "radianstodegrees")
                {
                    Console.WriteLine("Enter value in radians:");
                    if (double.TryParse(Console.ReadLine(), out double rad))
                    {
                        double deg = RadiansToDegrees(rad);
                        Console.WriteLine($"{rad} radians is {deg} degrees.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "degreestogradians")
                {
                    Console.WriteLine("Enter value in degrees:");
                    if (double.TryParse(Console.ReadLine(), out double deg))
                    {
                        double grad = DegreesToGradians(deg);
                        Console.WriteLine($"{deg} degrees is {grad} gradians.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "gradianstodegrees")
                {
                    Console.WriteLine("Enter value in gradians:");
                    if (double.TryParse(Console.ReadLine(), out double grad))
                    {
                        double deg = GradiansToDegrees(grad);
                        Console.WriteLine($"{grad} gradians is {deg} degrees.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "radianstogradians")
                {
                    Console.WriteLine("Enter value in radians:");
                    if (double.TryParse(Console.ReadLine(), out double rad))
                    {
                        double grad = RadiansToGradians(rad);
                        Console.WriteLine($"{rad} radians is {grad} gradians.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "gradianstoradians")
                {
                    Console.WriteLine("Enter value in gradians:");
                    if (double.TryParse(Console.ReadLine(), out double grad))
                    {
                        double rad = GradiansToRadians(grad);
                        Console.WriteLine($"{grad} gradians is {rad} radians.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "meterspersecondtokilometerspersecond")
                {
                    Console.WriteLine("Enter value in meters per second:");
                    if (double.TryParse(Console.ReadLine(), out double mps))
                    {
                        double kps = MetersPerSecondToKilometersPerSecond(mps);
                        Console.WriteLine($"{mps} m/s is {kps} km/s.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "kilometerspersecondtometerspersecond")
                {
                    Console.WriteLine("Enter value in kilometers per second:");
                    if (double.TryParse(Console.ReadLine(), out double kps))
                    {
                        double mps = KilometersPerSecondToMetersPerSecond(kps);
                        Console.WriteLine($"{kps} km/s is {mps} m/s.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "kilometerspersecondtomilespersecond")
                {
                    Console.WriteLine("Enter value in kilometers per second:");
                    if (double.TryParse(Console.ReadLine(), out double kps))
                    {
                        double mps = KilometersPerSecondToMilesPerSecond(kps);
                        Console.WriteLine($"{kps} km/s is {mps} mi/s.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "milespersecondtokilometerspersecond")
                {
                    Console.WriteLine("Enter value in miles per second:");
                    if (double.TryParse(Console.ReadLine(), out double mips))
                    {
                        double kps = MilesPerSecondToKilometersPerSecond(mips);
                        Console.WriteLine($"{mips} mi/s is {kps} km/s.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "milespersecondtomilesperhour")
                {
                    Console.WriteLine("Enter value in miles per second:");
                    if (double.TryParse(Console.ReadLine(), out double mips))
                    {
                        double mph = MilesPerSecondToMilesPerHour(mips);
                        Console.WriteLine($"{mips} mi/s is {mph} mph.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "milesperhourtomilespersecond")
                {
                    Console.WriteLine("Enter value in miles per hour:");
                    if (double.TryParse(Console.ReadLine(), out double mph))
                    {
                        double mips = MilesPerHourToMilesPerSecond(mph);
                        Console.WriteLine($"{mph} mph is {mips} mi/s.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "kilometersperhourtometerspersecond")
                {
                    Console.WriteLine("Enter value in kilometers per hour:");
                    if (double.TryParse(Console.ReadLine(), out double kmh))
                    {
                        double mps = KilometersPerHourToMetersPerSecond(kmh);
                        Console.WriteLine($"{kmh} km/h is {mps} m/s.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "meterspersecondtokilometersperhour")
                {
                    Console.WriteLine("Enter value in meters per second:");
                    if (double.TryParse(Console.ReadLine(), out double mps))
                    {
                        double kmh = MetersPerSecondToKilometersPerHour(mps);
                        Console.WriteLine($"{mps} m/s is {kmh} km/h.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "kilogramspercubicmetertogramspercubiccentimeter")
                {
                    Console.WriteLine("Enter value in kilograms per cubic meter:");
                    if (double.TryParse(Console.ReadLine(), out double kgm3))
                    {
                        double gcm3 = KilogramsPerCubicMeterToGramsPerCubicCentimeter(kgm3);
                        Console.WriteLine($"{kgm3} kg/m³ is {gcm3} g/cm³.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "gramspercubiccentimetertokilogramspercubicmeter")
                {
                    Console.WriteLine("Enter value in grams per cubic centimeter:");
                    if (double.TryParse(Console.ReadLine(), out double gcm3))
                    {
                        double kgm3 = GramsPerCubicCentimeterToKilogramsPerCubicMeter(gcm3);
                        Console.WriteLine($"{gcm3} g/cm³ is {kgm3} kg/m³.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "poundspercubicfoottokilogramspercubicmeter")
                {
                    Console.WriteLine("Enter value in pounds per cubic foot:");
                    if (double.TryParse(Console.ReadLine(), out double lbft3))
                    {
                        double kgm3 = PoundsPerCubicFootToKilogramsPerCubicMeter(lbft3);
                        Console.WriteLine($"{lbft3} lb/ft³ is {kgm3} kg/m³.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "kilogramspercubicmetertopoundspercubicfoot")
                {
                    Console.WriteLine("Enter value in kilograms per cubic meter:");
                    if (double.TryParse(Console.ReadLine(), out double kgm3))
                    {
                        double lbft3 = KilogramsPerCubicMeterToPoundsPerCubicFoot(kgm3);
                        Console.WriteLine($"{kgm3} kg/m³ is {lbft3} lb/ft³.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "poundspercubicinchtogramspercubiccentimeter")
                {
                    Console.WriteLine("Enter value in pounds per cubic inch:");
                    if (double.TryParse(Console.ReadLine(), out double lbin3))
                    {
                        double gcm3 = PoundsPerCubicInchToGramsPerCubicCentimeter(lbin3);
                        Console.WriteLine($"{lbin3} lb/in³ is {gcm3} g/cm³.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "gramspercubiccentimetertopoundspercubicinch")
                {
                    Console.WriteLine("Enter value in grams per cubic centimeter:");
                    if (double.TryParse(Console.ReadLine(), out double gcm3))
                    {
                        double lbin3 = GramsPerCubicCentimeterToPoundsPerCubicInch(gcm3);
                        Console.WriteLine($"{gcm3} g/cm³ is {lbin3} lb/in³.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "wattstohorsepower")
                {
                    Console.WriteLine("Enter value in watts:");
                    if (double.TryParse(Console.ReadLine(), out double watts))
                    {
                        double hp = WattsToHorsepower(watts);
                        Console.WriteLine($"{watts} W is {hp} horsepower.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "horsepowertowatts")
                {
                    Console.WriteLine("Enter value in horsepower:");
                    if (double.TryParse(Console.ReadLine(), out double hp))
                    {
                        double watts = HorsepowerToWatts(hp);
                        Console.WriteLine($"{hp} horsepower is {watts} W.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "kilowattstohorsepower")
                {
                    Console.WriteLine("Enter value in kilowatts:");
                    if (double.TryParse(Console.ReadLine(), out double kw))
                    {
                        double hp = KilowattsToHorsepower(kw);
                        Console.WriteLine($"{kw} kW is {hp} horsepower.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "horsepowertokilowatts")
                {
                    Console.WriteLine("Enter value in horsepower:");
                    if (double.TryParse(Console.ReadLine(), out double hp))
                    {
                        double kw = HorsepowerToKilowatts(hp);
                        Console.WriteLine($"{hp} horsepower is {kw} kW.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "megawattstohorsepower")
                {
                    Console.WriteLine("Enter value in megawatts:");
                    if (double.TryParse(Console.ReadLine(), out double mw))
                    {
                        double hp = MegawattsToHorsepower(mw);
                        Console.WriteLine($"{mw} MW is {hp} horsepower.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else if (input.ToLower() == "horsepowertomegawatts")
                {
                    Console.WriteLine("Enter value in horsepower:");
                    if (double.TryParse(Console.ReadLine(), out double hp))
                    {
                        double mw = HorsepowerToMegawatts(hp);
                        Console.WriteLine($"{hp} horsepower is {mw} MW.");
                    }
                    else { Console.WriteLine("Invalid input. Please enter a numeric value."); }
                }
                else
                {
                    Console.WriteLine("This program does not support dynamic command execution.");
                    Console.WriteLine("Please call the conversion functions directly from the code.");
                }
            }
        }
  }
}
