//NOTE: A significant portion of this code was generated by AI (ChatGPT-4) and then modified by me (Robert).
// run the command below in terminal to install prompt-sync if you haven't already:
// npm install prompt-sync
/*
NOTE:
You need Node.js installed to run this file in the terminal.
You also need the JavaScript extension installed in VS Code to run this file in the editor.

Change to the directory where your file is located

Then run the command inside your project directory:
node age_verification.js
*/

/*
PURPOSE:
This program is designed to verify if a user is old enough to access certain media content based on age ratings.
It checks the user's age against the age rating of the media and determines if access should be granted or denied.

FUNCTIONALITY:
When a user clicks on a media item, they will be sent to a terminal prompt that asks for their age, if the media age rating is 12+ or higher.
This is done to ensure the safety of the user's feelings.
*/
//Some of the code might be incomplete or untested. Please review and modify as necessary.
//You would input the values of the media below manually
const media = {
  Name: "South Park",
  //Valid media types: Movie, TV Show, Video Game, Book, Music, Podcast, Other
  Media_Type: "TV Show",
  /*
    Movie/Book Ratings: PG-13: 13+, R: 17+, NC-17: 18+
    TV Ratings: TV-14: 14+, TV-MA: 17+
    Video Game Ratings: T: 13+, M: 17+, AO: 18+
    Music/Podcast Ratings: Explicit: 18+
    Other Ratings: Custom age rating based on content
  */
  Age_Rating: 17,
  //Older content might have had looser standards as far as age ratings go.
  Year: 1997,
  Genre: "Animated, Comedy"
};
console.log("================================================================")
console.log("================================================================")
console.log("You have selected the following media:")
console.log("NAME: "+media.Name)
console.log("TYPE: "+media.Media_Type)
console.log("AGE RATING: "+media.Age_Rating+"+")
console.log("NOTE: rating standards may have been looser when this media was released.")
console.log("YEAR: "+media.Year)
console.log("GENRE: "+media.Genre)
console.log("================================================================")
console.log("================================================================")

// Calculate cutoff birthdate
const today = new Date();
const cutoffYear = today.getFullYear() - media.Age_Rating;
const cutoffDate = new Date(today.getMonth() + 1 + '/' + today.getDate() + '/' + cutoffYear);
const mm = String(today.getMonth() + 1).padStart(2, '0');
const dd = String(today.getDate()).padStart(2, '0');
const yy = String(cutoffYear).slice(-2);

console.log(`If you are born after ${mm}/${dd}/20${yy}, you will not be able to consume the following media.`);
console.log("================================================================");
const prompt = require('prompt-sync')(); // Add this line before using prompt
// Prompt user for birthdate
let User_Birthdate = prompt("Please enter your birthdate (MM/DD/YYYY): ");
// Validate input format (basic check)
while (!/^\d{2}\/\d{2}\/\d{4}$/.test(User_Birthdate)) {
  console.log("Invalid format. Please use MM/DD/YYYY.");
  User_Birthdate = prompt("Please enter your birthdate (MM/DD/YYYY): ");
}
console.log("================================================================")
if (new Date(User_Birthdate) > cutoffDate) {
  console.log("Access denied: You are not old enough to consume this media.");
  process.exit(0);
} else {
  console.log("Access granted: You are old enough to consume this media.");
}
console.log("================================================================")
console.log("================================================================")
console.log("IMPORTANT!!!")
console.log("/n/n")
console.log("Because this content is rated "+media.Age_Rating+" it is very likely to contain material that you might consider offensive or hateful.")
console.log("By typing the randomly generated 10-digit code below, you agree to the following terms:")
console.log("1. You will not hold the content creator(s) or distributor(s) liable for any emotional distress or offense caused by consuming this media.")
console.log("2. You acknowledge that you are voluntarily choosing to consume this content despite its potentially offensive nature.")
console.log("3. You understand that the content may include, but is not limited to, strong language, violence, sexual content, or other mature themes.")
console.log("4. I fully understand and recognize that the consequences of lying about my age are of but not limited to jail, fines, and lawsuits.")
console.log("5. I also recognize that if I distribute this content to underage individuals, I may face legal consequences.")
console.log("6. I possess the maturity to handle such content.")
console.log("7. I recognize the risks associated with this type of content.")
function getRandomInt(min, max) {
  min = Math.ceil(min); // Ensure min is an integer
  max = Math.floor(max); // Ensure max is an integer
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

// Generate a 10-digit random code as a string
const Code_Generated = getRandomInt(1000000000, 9999999999).toString();
console.log(Code_Generated);
const User_Code = prompt("Type 0 to refuse agreement to any of the conditions above and exit safely.\nP.s. If you did lie about your age prior, now is the time to exit immediately and avoid potential legal consequences later on.\nEnter the 10-digit code to agree: ");

if (User_Code === Code_Generated) {
    console.log("Thank you for agreeing to the terms. You may now proceed to consume the media.");
    // Simulate a delay
    setTimeout(() => {
        // You need to input your own URL below
        const Continue_URL = "URL HERE";
        console.log(`Navigate to: ${Continue_URL}`);
    }, 3000);
} else {
    console.log("You have chosen not to agree to the terms. You will now exit safely. Goodbye.");
    setTimeout(() => process.exit(0), 3000);
}
