/*
IMPORTANT: Most of this code was generated by Microsoft's AI, Copilot (and then later tested and modified by me).
Therefore, it may contain errors or not work as intended. Please review and test the code before using it in a production environment.
IMPORTANT: This program is made by an indie developer and is not affiliated with or endorsed by any company or organization.
IMPORTANT: This program is not intended to be a professional solution and may not follow best practices or coding standards.
IMPORTANT: I am new to C++ and programming in general, so please forgive any mistakes or misunderstandings.

LANGUAGE VERSION: C++11 (compatible with GCC and MSVC)

NOTE: Because of the previously mentioned statement, I may struggle with more advanced concepts or syntax.
NOTE: This program is intended for you and me to learn from and improve upon.
NOTE: This program is not intended to be a complete or fully functional program.
NOTE: This program is meant to demonstrate basic C++ concepts and is not meant to be a complete or fully functional program.

To run the program, 
1. Have C/C++ extension installed in your VS Code editor.
2. Install GCC compiler from https://jmeubank.github.io/tdm-gcc/
3. Test the installation by running `gcc --version` in the terminal.
4. Restart VS Code and your terminal after installation.
5. Open the terminal in VS Code.
6. Navigate to the directory where this file is located.
7. Compile and run the program with the following Powershell command:
g++ quick_maths.cpp -o quick_maths.exe 
.\quick_maths.exe

NOTE: If you try to run the program with `gcc` instead of `g++`, you will get an error.
NOTE: If you try to run the following command all in one line 
(g++ quick_maths.cpp -o quick_maths.exe .\quick_maths.exe), you will get an error.
*/

//Quick Maths is a simple math game that challenges the player to answer as many math questions as possible correctly.
//uses xp to increase the level of the player 1-10, which increases the difficulty of the questions asked in the prompt,
//and each level requires an additional 100 xp to level up to the next level. The maximum level is 10. The player earns 100 xp for each correct answer and loses 1 live for each incorrect answer.
//the player starts with 3 lives and the game ends when the player loses all lives.
//there is a scoreboard that keeps track of the player's score and displays it at the end of the game.
//functions needed: main(), generateMathProblems(), checkAnswer(), updateScoreboard(), displayScoreboard(),
//levelUp(), gameOver()
//classes needed: Player, Scoreboard

#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;

// Forward declarations
class Player;
class Scoreboard;

void generateMathProblems(Player &player, Scoreboard &scoreboard);
bool checkAnswer(int correctAnswer, int playerAnswer, Player &player);
void updateScoreboard(Scoreboard &scoreboard, bool correct);
void displayScoreboard(const Scoreboard &scoreboard);
void levelUp(Player &player);
void gameOver(const Scoreboard &scoreboard);

// ------------------ Player Class ------------------
class Player {
public:
    int level;
    int xp;
    int lives;

    Player() {
        level = 1;
        xp = 0;
        lives = 3;
    }

    void addXP(int amount) {
        xp += amount;
        int xpNeeded = level * 100;
        if (xp >= xpNeeded && level < 10) {
            xp -= xpNeeded;
            levelUp(*this);
        }
    }

    void loseLife() {
        lives--;
    }

    bool isAlive() const {
        return lives > 0;
    }
};

// ------------------ Scoreboard Class ------------------
class Scoreboard {
public:
    int score;

    Scoreboard() {
        score = 0;
    }

    void addPoints(int points) {
        score += points;
    }
};

// ------------------ Functions ------------------
void generateMathProblems(Player &player, Scoreboard &scoreboard) {
    int maxNumber = player.level * 10; // difficulty scales with level
    int a = rand() % maxNumber + 1;
    int b = rand() % maxNumber + 1;
    int correctAnswer = a + b;

    cout << "Level " << player.level << " | Lives: " << player.lives 
         << " | XP: " << player.xp << "\n";
    cout << "Solve: " << a << " + " << b << " = ";
    int playerAnswer;
    cin >> playerAnswer;

    bool correct = checkAnswer(correctAnswer, playerAnswer, player);
    updateScoreboard(scoreboard, correct);
}

bool checkAnswer(int correctAnswer, int playerAnswer, Player &player) {
    if (playerAnswer == correctAnswer) {
        cout << "Correct! +100 XP\n";
        player.addXP(100);
        return true;
    } else {
        cout << "Wrong! You lose 1 life.\n";
        player.loseLife();
        return false;
    }
}

void updateScoreboard(Scoreboard &scoreboard, bool correct) {
    if (correct) {
        scoreboard.addPoints(10);
    }
}

void displayScoreboard(const Scoreboard &scoreboard) {
    cout << "\n===== FINAL SCORE =====\n";
    cout << "Score: " << scoreboard.score << endl;
    cout << "=======================\n";
}

void levelUp(Player &player) {
    player.level++;
    cout << "🎉 Level Up! You are now Level " << player.level << "!\n";
}

void gameOver(const Scoreboard &scoreboard) {
    cout << "\n💀 Game Over! 💀\n";
    displayScoreboard(scoreboard);
}

// ------------------ Main ------------------
int main() {
    srand(time(0)); // seed random numbers

    Player player;
    Scoreboard scoreboard;

    cout << "=== Welcome to Quick Maths! ===\n";

    while (player.isAlive() && player.level <= 10) {
        generateMathProblems(player, scoreboard);
    }

    gameOver(scoreboard);
    return 0;
}
