#!/bin/bash
#VERY IMPORTANT: AI generated by GitHub Copilot, then modified by me.
#VERY IMPORTANT: Not everything is fully tested. May contain bugs.

#LANGUAGE VERSION: Bash 4.x or later recommended

#IMPORTANT: This script is basic, and may not cover all edge cases.
#IMPORTANT: For educational purposes only. Review and modify code as needed before use.
#IMPORTANT: May require sudo privileges for certain operations.
#IMPORTANT: Always test scripts in a safe environment before deploying.
#IMPORTANT: This script is provided "as is" without warranty of any kind.
#IMPORTANT: This script is not sponsored by nor affiliated with any organization.

#NOTE: This script is a starting point and can be expanded with more features.
#NOTE: This script is intended for Linux systems. Some commands may differ on other OSes.
#NOTE: Ensure you have necessary permissions to execute system commands.
#NOTE: This script is generated to help me learn bash scripting.
#NOTE: Use at your own risk. The author is not responsible for any damage caused.
#NOTE: Always back up important data before running scripts that modify system settings.
#NOTE: This script may require additional packages to be installed depending on your Linux distribution.
#NOTE: Modify paths and commands as necessary to fit your specific use case.
#NOTE: This script is a simple demonstration and may not be suitable for production use.

#On VScode, install Shellcheck and Bash IDE extensions for best results.
# IT Tools Suite - A simple menu-driven script for common IT tasks
# to run in Linux:
# chmod +x it_tools_suite.sh
# ./it_tools_suite.sh
while true; do
    echo "===== IT Tools Suite ====="
    echo "1. System Information"
    echo "2. User Management"
    echo "3. Service Status"
    echo "4. Network Tools"
    echo "5. Disk Usage"
    echo "6. Backup Utility"
    echo "7. Log Viewer"
    echo "8. Software Updates"
    echo "9. Process Monitor"
    echo "10. File Search"
    echo "11. Help/Instructions"
    echo "0. Exit"
    read -p "Choose an option: " choice

    case $choice in
        1) uname -a; free -h; df -h ;;
        2) cat /etc/passwd; last ;;
        3) systemctl status ssh; systemctl status apache2 ;;
        4) read -p "Enter host to ping: " host; ping -c 4 $host ;;
        5) du -sh /* ;;
        6) tar -czvf "backup_$(date +%F).tar.gz" /path/to/backup ;;
        7) tail -n 50 /var/log/syslog ;;
        8) sudo apt update && sudo apt upgrade -y ;;
        9) ps aux; read -p "PID to kill: " pid; kill $pid ;;
        10) read -p "Filename to search: " fname; find / -name "$fname" ;;
        11)
            echo "===== Help / Instructions ====="
            echo "1. System Information: Shows system, memory, and disk info."
            echo "2. User Management: Lists users and last login times."
            echo "3. Service Status: Checks status of SSH and Apache services."
            echo "4. Network Tools: Pings a host to test connectivity."
            echo "5. Disk Usage: Shows disk usage for directories."
            echo "6. Backup Utility: Creates a compressed backup of a folder."
            echo "7. Log Viewer: Displays the last 50 lines of the system log."
            echo "8. Software Updates: Updates and upgrades system packages."
            echo "9. Process Monitor: Lists processes and allows killing by PID."
            echo "10. File Search: Finds files by name."
            echo "0. Exit: Quits the tool suite."
            echo "==============================="
            ;;
        0) break ;;
        *) echo "Invalid option." ;;
    esac
    echo ""
done
