import java.io.*;
import java.lang.reflect.Method;
import java.util.*;
import java.util.concurrent.*;

public class espresso_cash{
    //NOTE: Significant portions of this code are autocompleted and/or generated by AI.
    //As a result, there may be some errors or bugs in the code.
    //Please review the code carefully and make any necessary adjustments.
    //I don't fully understand some of the commands used, as I am still learning Java.
    //If you find any errors or bugs, please let me know so I can fix them

    //NOTE: The program currently does not save session data between runs.
    //I am working on implementing a feature to save the state of the application to a file
    
    //IMPORTANT: the serialize and deserialize methods are autocompleted by AI and are not fully implemented yet.
    //They are supposed to save the state of the application to a file and load it back

    //IMPORTANT: the balance variable doesn't visually update in the terminal after deposits and withdrawals.
    //It is currently a known issue and I am working on fixing it.

    /*
        NOTE:
        You need to install Java Development Kit (JDK) to run this file in the terminal.
        1. Download JDK from: https://www.oracle.com/java/technologies/javase-jdk11-downloads.html
        2. Install JDK and set up the environment variables (PATH).
        3. Restart your terminal/command prompt.
        4. Check if Java is installed by running the command: java -version
        5. Check if javac is installed by running the command: javac -version
        6. If both commands return a version number, you are good to go!
        To be able to run this file in terminal, run the command listed below:
        cd "c:\Users\Rober\OneDrive\Desktop\Coding Projects"
        then run:
        java espresso_cash.java
    */
    /*
        This program is a simple money application that
        1. make withdrawals and deposits.
        2. check the balance.
        3. budget expenses.
    */
    private double balance = 10000.0;
    public static double income = 0.0;
    public static double total_budget_expenses = 0.0;
    // Fixed Expenses
    public static double rent_mortgage = 1200.0;
    public static double internet_phone = 100.0;
    public static double insurance = 200.0;
    public static double loan_payments = 150.0;
    public static double subscriptions = 50.0;
    // Variable Expenses
    public static double utilities = 150.0;
    public static double groceries = 300.0;
    public static double transportation = 100.0;
    public static double dining_entertainment = 200.0;
    public static double clothing_personal_care = 100.0;
    public static double medical_healthcare = 100.0;
    public static double miscellaneous = 100.0;
    // Savings & Investments
    public static double retirement_contributions = 200.0;
    public static double emergency_fund = 100.0;
    public static double investment_contributions = 150.0;
    public static double education_savings = 100.0;
    public static double other_savings = 100.0;
    static {
        income = 3000.0;
        total_budget_expenses = rent_mortgage + internet_phone + insurance + loan_payments + subscriptions +
                                utilities + groceries + transportation + dining_entertainment + clothing_personal_care +
                                medical_healthcare + miscellaneous + retirement_contributions + emergency_fund +
                                investment_contributions + education_savings + other_savings;
    }
    public double getBalance() {
        return balance;   
    }
    static void update(){
            System.out.println("Hello, Espresso Cash!");
            System.out.println("========================================================");
            System.out.println("This is a simple money application that can:");
            System.out.println("1. Make withdrawals and deposits.");
            System.out.println("2. Check the balance.");
            System.out.println("3. Budget expenses.");
            System.out.println("========================================================");
            System.out.println("Balance: $ "+ new espresso_cash().getBalance());
            System.out.println("Total Income: $ " + income);
            System.out.println("========================================================");
            System.out.println("Total Budget Expenses: $" + total_budget_expenses);
            System.out.println("--------------------------------------------------------");
            System.out.println("Budget Categories: F = Fixed Expenses, V = Variable Expenses, SI = Savings & Investments");
            System.out.println("--------------------------------------------------------");
            System.out.println("F: Rent/mortgage $" + rent_mortgage);
            System.out.println("F: Internet and phone bills $" + internet_phone);
            System.out.println("F: Insurance (health, auto, home) $" + insurance);
            System.out.println("F: Loan payments (student, auto, personal) $" + loan_payments);
            System.out.println("F: Subscriptions (streaming services, gym memberships) $" + subscriptions);
            System.out.println("V: Utilities (electricity, water, gas $)" + utilities);
            System.out.println("V: Groceries $" + groceries);
            System.out.println("V: Transportation (fuel, public transit, ride-sharing) $" + transportation);
            System.out.println("V: Dining out and entertainment $" + dining_entertainment);
            System.out.println("V: Clothing and personal care $" + clothing_personal_care);
            System.out.println("V: Medical and healthcare expenses $" + medical_healthcare);
            System.out.println("V: Miscellaneous (gifts, donations, hobbies) $" + miscellaneous);
            System.out.println("SI: Retirement contributions (401(k), IRA) $" + retirement_contributions);
            System.out.println("SI: Emergency fund savings $" + emergency_fund);
            System.out.println("SI: Investment account contributions (stocks, bonds, mutual funds) $" + investment_contributions);
            System.out.println("SI: Education savings (529 plan, education fund) $" + education_savings);
            System.out.println("SI: Other savings goals (vacation, down payment on a house) $" + other_savings);
            System.out.println("========================================================");
            System.out.println("Type the following commands to use the application: (type 'e' to exit)");
            System.out.println("'d' <amount> to deposit");
            System.out.println("'w' <amount> to withdraw");
            System.out.println("'i' <amount> to change income");
            System.out.println("F1 <amount> to change Rent/mortgage amount");
            System.out.println("F2 <amount> to change Internet and phone bills amount");
            System.out.println("F3 <amount> to change Insurance (health, auto, home) amount");
            System.out.println("F4 <amount> to change Loan payments (student, auto, personal) amount");
            System.out.println("F5 <amount> to change Subscriptions (streaming services, gym memberships");
            System.out.println("V1 <amount> to change Utilities (electricity, water, gas) amount");
            System.out.println("V2 <amount> to change Groceries amount");
            System.out.println("V3 <amount> to change Transportation (fuel, public transit, ride-sharing) amount");
            System.out.println("V4 <amount> to change Dining out and entertainment amount");
            System.out.println("V5 <amount> to change Clothing and personal care amount");
            System.out.println("V6 <amount> to change Medical and healthcare expenses amount");
            System.out.println("V7 <amount> to change Miscellaneous (gifts, donations, hobbies) amount");
            System.out.println("SI1 <amount> to change Retirement contributions (401(k), IRA) amount");
            System.out.println("SI2 <amount> to change Emergency fund savings amount");
            System.out.println("SI3 <amount> to change Investment account contributions (stocks, bonds, mutual funds");
            System.out.println("SI4 <amount> to change Education savings (529 plan, education fund) amount");
            System.out.println("SI5 <amount> to change Other savings goals (vacation, down payment on a house) amount");
            System.out.println("========================================================");
        }
    //Work In Progress: This feature is not fully implemented yet.
    //It is supposed to save the state of the application to a file and load it back
    public static void serialize() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("espresso_cash.ser"))) {
            espresso_cash app = new espresso_cash();
            oos.writeObject(app);
            System.out.println("Application state saved.");
        } catch (IOException e) {
            System.out.println("Error saving application state: " + e.getMessage());
        }
    }
    //Work In Progress: This feature is not fully implemented yet.
    //It is supposed to save the state of the application to a file and load it back
    public static espresso_cash deserialize() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("espresso_cash.ser"))) {
            espresso_cash app = (espresso_cash) ois.readObject();
            System.out.println("Application state loaded.");
            return app;
        } catch (IOException | ClassNotFoundException e) {
            System.out.println("Error loading application state: " + e.getMessage());
            return new espresso_cash();
        }
    }
    public static void main(String[] args) {
        deserialize();
        update();
        Scanner scanner = new Scanner(System.in);
        espresso_cash app = new espresso_cash();
        while (true) {
            System.out.print("Enter command: ");
            String input = scanner.nextLine();
            String[] parts = input.split(" ");
            String command = parts[0];
            if (command.equals("e")) {
                System.out.println("Exiting the application. Goodbye!");
                break;
            } else if (command.equals("d")) {
                if (parts.length != 2) {
                    System.out.println("Invalid command. Usage: d <amount>");
                    continue;
                }
                try {
                    double amount = Double.parseDouble(parts[1]);
                    if (amount <= 0) {
                        System.out.println("Deposit amount must be positive.");
                        continue;
                    }
                    app.balance += amount;
                    System.out.println("Deposited: $ " + amount);
                    System.out.println("New Balance: $ " + app.getBalance());
                    serialize();
                    update();
                } catch (NumberFormatException e) {
                    System.out.println("Invalid amount. Please enter a numeric value.");
                }
            } else if (command.equals("w")) {
                if (parts.length != 2) {
                    System.out.println("Invalid command. Usage: w <amount>");
                    continue;
                }
                try {
                    double amount = Double.parseDouble(parts[1]);
                    if (amount <= 0) {
                        System.out.println("Withdrawal amount must be positive.");
                        continue;
                    }
                    if (amount > app.balance) {
                        System.out.println("Insufficient funds for this withdrawal.");
                        continue;
                    }
                    app.balance -= amount;
                    System.out.println("Withdrew: $ " + amount);
                    System.out.println("New Balance: $ " + app.getBalance());
                    serialize();
                    update();
                } catch (NumberFormatException e) {
                    System.out.println("Invalid amount. Please enter a numeric value.");
                }
            } else if (command.equals("i")) {
                if (parts.length != 2) {
                    System.out.println("Invalid command. Usage: i <new_income>");
                    continue;
                }
                try {
                    double newIncome = Double.parseDouble(parts[1]);
                    if (newIncome < 0) {
                        System.out.println("Income must be non-negative.");
                        continue;
                    }
                    income = newIncome;
                    System.out.println("Income updated to: $ " + income);
                    serialize();
                    update();
                } catch (NumberFormatException e) {
                    System.out.println("Invalid income. Please enter a numeric value.");
                    continue;
                }
            } else if (command.matches("F[1-5]|V[1-7]|SI[1-5]")) {
                if (parts.length != 2) {
                    System.out.println("Invalid command. Usage: " + command + " <new_amount>");
                    continue;
                }
                try {
                    double newAmount = Double.parseDouble(parts[1]);
                    if (newAmount < 0) {
                        System.out.println("Amount must be non-negative.");
                        continue;
                    }
                    switch (command) {
                        case "F1":
                            rent_mortgage = newAmount;
                            serialize();
                            update();
                            break;
                        case "F2":
                            internet_phone = newAmount;
                            serialize();
                            update();
                            break;
                        case "F3":
                            insurance = newAmount;
                            serialize();
                            update();
                            break;
                        case "F4":
                            loan_payments = newAmount;
                            serialize();
                            update();
                            break;
                        case "F5":
                            subscriptions = newAmount;
                            serialize();
                            update();
                            break;
                        case "V1":
                            utilities = newAmount;
                            serialize();
                            update();
                            break;
                        case "V2":
                            groceries = newAmount;
                            serialize();
                            update();
                            break;
                        case "V3":
                            transportation = newAmount;
                            serialize();
                            update();
                            break;
                        case "V4":
                            dining_entertainment = newAmount;
                            serialize();
                            update();
                            break;
                        case "V5":
                            clothing_personal_care = newAmount;
                            serialize();
                            update();
                            break;
                        case "V6":
                            medical_healthcare = newAmount;
                            serialize();
                            update();
                            break;
                        case "V7":
                            miscellaneous = newAmount;
                            serialize();
                            update();
                            break;
                        case "SI1":
                            retirement_contributions = newAmount;
                            serialize();
                            update();
                            break;
                        case "SI2":
                            emergency_fund = newAmount;
                            serialize();
                            update();
                            break;
                        case "SI3":
                            investment_contributions = newAmount;
                            serialize();
                            update();
                            break;
                        case "SI4":
                            education_savings = newAmount;
                            serialize();
                            update();
                            break;
                        case "SI5":
                            other_savings = newAmount;
                            serialize();
                            update();
                            break;
                        default:
                            System.out.println("Unknown command.");
                            continue;
                    }
                } catch (NumberFormatException e) {
                    System.out.println("Invalid amount. Please enter a numeric value.");
                    continue;
                }
            }
        }
    }
}
