#!/usr/bin/env bash
# NOTE: Portions of this script were generated by an AI assistant and then
# reviewed/modified by the repository owner. The generated instructions may be
# incomplete or incorrect for your environment. Always review commands before running them.

# build.sh - simple POSIX build helper for clock_asm
# Tries NASM (elf64) and links with ld if available.

set -eu
IFS=$'\n\t'

# Move to script directory
root="$(cd "$(dirname "$0")" && pwd)"
cd "$root"

if [ ! -f "clock_asm.asm" ]; then
    echo "ERROR: clock_asm.asm not found in project root" >&2
    exit 1
fi

if command -v nasm >/dev/null 2>&1; then
    echo "Using nasm to assemble (ELF64 target)"
    if nasm -f elf64 "clock_asm.asm" -o "clock_asm.o"; then
        if command -v ld >/dev/null 2>&1; then
            echo "Linking with ld..."
            ld "clock_asm.o" -o "clock_asm"
            echo "Built: ./clock_asm"
            exit 0
        else
            echo "nasm produced object: clock_asm.o (no ld found to link)" >&2
            echo "You can run the object on platforms that support ELF binfmt, or install ld to link." >&2
            exit 0
        fi
    else
        echo "nasm failed. You may need different format flags or source changes." >&2
        exit 2
    fi
else
    echo "nasm not installed. Please install nasm and re-run this script." >&2
    exit 3
fi
