"""Generate a .pot template for PowerApp.

Primary mechanism: try to run `xgettext` if available. If not, fall back to a
simple Python extraction that scans for _('...') patterns.

Usage: python scripts/generate_pot.py [--output locale/powerapp.pot]
"""
import re
import subprocess
from pathlib import Path

DEFAULT_OUT = Path('locale') / 'powerapp.pot'


def _extract_with_xgettext(root: Path, out: Path) -> bool:
    try:
        files = [str(p) for p in root.rglob('*.py')]
        if not files:
            return False
        cmd = ['xgettext', '--language=Python', '--keyword=_', '--output', str(out)] + files
        subprocess.run(cmd, check=True)
        return True
    except Exception:
        return False


def _simple_extract(root: Path, out: Path):
    pattern = re.compile(r"_\(\s*(['\"])(.*?)\1\s*\)", re.DOTALL)
    msgs = set()
    for p in root.rglob('*.py'):
        try:
            txt = p.read_text(encoding='utf-8')
            for m in pattern.findall(txt):
                msgs.add(m[1])
        except Exception:
            continue
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open('w', encoding='utf-8') as fh:
        fh.write('#. POT file generated by scripts/generate_pot.py\n')
        fh.write('msgid ""\nmsgstr ""\n"Project-Id-Version: PowerApp\\n"\n"MIME-Version: 1.0\\n"\n\n')
        for msg in sorted(msgs):
            fh.write('\nmsgid "{}"\nmsgstr ""\n'.format(msg.replace('"', '\\"')))


def generate_pot(root: str = '.', out: str = None):
    r = Path(root).resolve()
    o = Path(out) if out else DEFAULT_OUT
    # try xgettext first
    ok = _extract_with_xgettext(r, o)
    if not ok:
        _simple_extract(r, o)
    return o


if __name__ == '__main__':
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument('--root', default='.', help='Project root to scan')
    p.add_argument('--output', default=str(DEFAULT_OUT), help='Output POT file')
    args = p.parse_args()
    path = generate_pot(args.root, args.output)
    print('Generated', path)