/*
  IMPORTANT: Most code was generated by AI, please review carefully for errors.
  IMPORTANT: I have a limited understanding of SQL, and therefore, this code is NOT
  meant to be used in high-stakes scenarios involving lives and/or money.
  IMPORTANT: This program is meant for educational purposes, and it is not sponsored by,
  nor endorsed big tech firms like Google or Microsoft.

  NOTE: Run specific portions of code at a time to avoid crashing the program.

  CITATION for instructions: https://www.youtube.com/watch?v=9ADd-_mM5Dw
  VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
  To install:
  1. Go to Visual Code.
  2. Download the "SQLTools" extension.
  3. Download another extension that starts with "SQLTools" following with the desired 
  RDBMS (Relational DataBase Management System) such as MySQL.
  4. Go to "Add New Connection" under the new cylinder DB button added to your left-hand bar.
  5. Select your desired RDBMS.
  6. Input your connection name, username, and database.
  7. Add an additional '0' to the given port number to make it '33060.'
  8. Change password to plaintext in settings and type in your password.
  9. Change authentication protocal to "xprotocol."
  10. Specify a connection time-out setting (e.x. 30).
  IMPORTANT: steps 11 - 14 are MySQL specific.
  ------------------------------------------------------------------------------------------------------
  11. Go onto https://dev.mysql.com/downloads/file/?id=544662 to download the dependencies.
  12. Follow the wizard.
  13. Go onto your PowerShell, and type:
  & "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -u YOUR_USERNAME -p
  14. Once you have "mysql>" on the left as your input, type the following command:
  CREATE DATABASE your_database;
  ------------------------------------------------------------------------------------------------------
  15. Save connection.
  16. Click on the "plug icon" to connect to the database, and be in your database.
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
*/
-- 1. Create and switch to your database
CREATE DATABASE IF NOT EXISTS biz_intelli_db;
USE biz_intelli_db;

-- 2. Create a sales table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS Sales (
    id INT PRIMARY KEY,
    product VARCHAR(50),
    amount DECIMAL(10,2)
);

-- 3. Reset table so inserts don’t duplicate
TRUNCATE TABLE Sales;

-- 4. Insert some sample data
INSERT INTO Sales VALUES
(1, 'Bike', 500.00),
(2, 'Weights', 50.00),
(3, 'Bottle', 10.00),
(4, 'Pants', 20.00),
(5, 'Shirt', 10.00),
(6, 'Monitor', 300.00),
(7, 'Bread', 3.00),
(8, 'Laptop', 1500.00),
(9, 'Plushy', 20.00),
(10, 'Helmet', 55.00);

-- 5. Basic BI queries

-- Total sales by product
SELECT product, SUM(amount) AS total_sales
FROM Sales
GROUP BY product;

-- Average sale amount
SELECT AVG(amount) AS average_sale
FROM Sales;

-- Highest single sale
SELECT product, amount
FROM Sales
ORDER BY amount DESC
LIMIT 1;

-- Lowest single sale
SELECT product, amount
FROM Sales
ORDER BY amount
LIMIT 1;
