-- ============================================================================
-- Grey Legacy - Insurance Claims Processing System
-- Database Schema DDL
-- ============================================================================
-- Target: H2 (dev) / PostgreSQL (production)
-- Generated from Hibernate entity mappings
-- ============================================================================

-- Sequences
CREATE SEQUENCE IF NOT EXISTS POLICY_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS CLAIM_SEQ START WITH 5000 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PAYMENT_SEQ START WITH 10000 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS AUDIT_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS NOTE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SNAPSHOT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ENDORSEMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ADJUSTER_SEQ START WITH 100 INCREMENT BY 1;

-- ============================================================================
-- POLICY table
-- ============================================================================
CREATE TABLE POLICY (
    ID                  BIGINT          NOT NULL DEFAULT NEXT VALUE FOR POLICY_SEQ,
    VERSION             INTEGER         DEFAULT 0,
    POLICY_NUMBER       VARCHAR(20)     NOT NULL,
    STATUS              VARCHAR(20)     NOT NULL,
    POLICY_TYPE         VARCHAR(30)     NOT NULL,
    HOLDER_FIRST_NAME   VARCHAR(50)     NOT NULL,
    HOLDER_LAST_NAME    VARCHAR(50)     NOT NULL,
    HOLDER_SSN          VARCHAR(11),
    HOLDER_EMAIL        VARCHAR(100),
    HOLDER_PHONE        VARCHAR(20),
    EFFECTIVE_DATE      DATE            NOT NULL,
    EXPIRATION_DATE     DATE            NOT NULL,
    PREMIUM_AMOUNT      DECIMAL(12,2),
    COVERAGE_LIMIT      DECIMAL(14,2),
    DEDUCTIBLE          DECIMAL(10,2),
    AGENT_CODE          VARCHAR(10),
    UNDERWRITER_CODE    VARCHAR(10),
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_POLICY PRIMARY KEY (ID),
    CONSTRAINT UK_POLICY_NUMBER UNIQUE (POLICY_NUMBER)
);

CREATE INDEX IDX_POLICY_STATUS ON POLICY(STATUS);
CREATE INDEX IDX_POLICY_HOLDER ON POLICY(HOLDER_LAST_NAME);
CREATE INDEX IDX_POLICY_DATES ON POLICY(EFFECTIVE_DATE, EXPIRATION_DATE);

-- ============================================================================
-- CLAIM table
-- ============================================================================
CREATE TABLE CLAIM (
    ID                  BIGINT          NOT NULL DEFAULT NEXT VALUE FOR CLAIM_SEQ,
    VERSION             INTEGER         DEFAULT 0,
    CLAIM_NUMBER        VARCHAR(20)     NOT NULL,
    POLICY_ID           BIGINT          NOT NULL,
    STATUS              VARCHAR(20)     NOT NULL,
    CLAIM_TYPE          VARCHAR(30)     NOT NULL,
    LOSS_DATE           DATE            NOT NULL,
    REPORTED_DATE       TIMESTAMP       NOT NULL,
    LOSS_DESCRIPTION    VARCHAR(2000),
    LOSS_LOCATION       VARCHAR(200),
    CLAIMANT_FIRST_NAME VARCHAR(50)     NOT NULL,
    CLAIMANT_LAST_NAME  VARCHAR(50)     NOT NULL,
    CLAIMANT_PHONE      VARCHAR(50),
    CLAIMANT_EMAIL      VARCHAR(100),
    ADJUSTER_CODE       VARCHAR(10),
    ESTIMATED_LOSS      DECIMAL(14,2),
    APPROVED_AMOUNT     DECIMAL(14,2),
    DEDUCTIBLE_APPLIED  DECIMAL(10,2),
    FRAUD_RISK_LEVEL    VARCHAR(20),
    FRAUD_SCORE         INTEGER,
    FRAUD_SCORED_DATE   TIMESTAMP,
    CLOSED_DATE         TIMESTAMP,
    CLOSED_REASON       VARCHAR(500),
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_CLAIM PRIMARY KEY (ID),
    CONSTRAINT UK_CLAIM_NUMBER UNIQUE (CLAIM_NUMBER),
    CONSTRAINT FK_CLAIM_POLICY FOREIGN KEY (POLICY_ID) REFERENCES POLICY(ID)
);

CREATE INDEX IDX_CLAIM_POLICY ON CLAIM(POLICY_ID);
CREATE INDEX IDX_CLAIM_STATUS ON CLAIM(STATUS);
CREATE INDEX IDX_CLAIM_LOSS_DATE ON CLAIM(LOSS_DATE);
CREATE INDEX IDX_CLAIM_ADJUSTER ON CLAIM(ADJUSTER_CODE);
CREATE INDEX IDX_CLAIM_FRAUD ON CLAIM(FRAUD_RISK_LEVEL);

-- ============================================================================
-- CLAIM_PAYMENT table
-- ============================================================================
CREATE TABLE CLAIM_PAYMENT (
    ID                  BIGINT          NOT NULL DEFAULT NEXT VALUE FOR PAYMENT_SEQ,
    VERSION             INTEGER         DEFAULT 0,
    CLAIM_ID            BIGINT          NOT NULL,
    PAYMENT_NUMBER      VARCHAR(20)     NOT NULL,
    PAYMENT_STATUS      VARCHAR(20)     NOT NULL,
    PAYMENT_METHOD      VARCHAR(20),
    AMOUNT              DECIMAL(14,2)   NOT NULL,
    SCHEDULED_DATE      DATE,
    PROCESSED_DATE      TIMESTAMP,
    PAYEE_NAME          VARCHAR(100)    NOT NULL,
    PAYEE_ADDRESS       VARCHAR(200),
    CHECK_NUMBER        VARCHAR(20),
    MEMO                VARCHAR(500),
    APPROVED_BY         VARCHAR(50),
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_PAYMENT PRIMARY KEY (ID),
    CONSTRAINT UK_PAYMENT_NUMBER UNIQUE (PAYMENT_NUMBER),
    CONSTRAINT FK_PAYMENT_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM(ID)
);

CREATE INDEX IDX_PAYMENT_CLAIM ON CLAIM_PAYMENT(CLAIM_ID);
CREATE INDEX IDX_PAYMENT_STATUS ON CLAIM_PAYMENT(PAYMENT_STATUS);

-- ============================================================================
-- CLAIM_AUDIT table (append-only)
-- ============================================================================
CREATE TABLE CLAIM_AUDIT (
    ID                  BIGINT          NOT NULL DEFAULT NEXT VALUE FOR AUDIT_SEQ,
    VERSION             INTEGER         DEFAULT 0,
    CLAIM_ID            BIGINT          NOT NULL,
    EVENT_TIMESTAMP     TIMESTAMP       NOT NULL,
    EVENT_TYPE          VARCHAR(50)     NOT NULL,
    PREVIOUS_VALUE      VARCHAR(500),
    NEW_VALUE           VARCHAR(500),
    PERFORMED_BY        VARCHAR(50)     NOT NULL,
    DESCRIPTION         VARCHAR(1000),
    IP_ADDRESS          VARCHAR(45),
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_AUDIT PRIMARY KEY (ID),
    CONSTRAINT FK_AUDIT_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM(ID)
);

CREATE INDEX IDX_AUDIT_CLAIM ON CLAIM_AUDIT(CLAIM_ID);
CREATE INDEX IDX_AUDIT_EVENT_TYPE ON CLAIM_AUDIT(EVENT_TYPE);
CREATE INDEX IDX_AUDIT_TIMESTAMP ON CLAIM_AUDIT(EVENT_TIMESTAMP);

-- ============================================================================
-- CLAIM_NOTE table
-- ============================================================================
CREATE TABLE CLAIM_NOTE (
    ID                  BIGINT          NOT NULL DEFAULT NEXT VALUE FOR NOTE_SEQ,
    VERSION             INTEGER         DEFAULT 0,
    CLAIM_ID            BIGINT          NOT NULL,
    NOTE_TYPE           VARCHAR(30),
    SUBJECT             VARCHAR(200)    NOT NULL,
    CONTENT             CLOB,
    AUTHOR_NAME         VARCHAR(50)     NOT NULL,
    CONFIDENTIAL        BOOLEAN         DEFAULT FALSE,
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_NOTE PRIMARY KEY (ID),
    CONSTRAINT FK_NOTE_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM(ID)
);

CREATE INDEX IDX_NOTE_CLAIM ON CLAIM_NOTE(CLAIM_ID);

-- ============================================================================
-- CLAIM_SNAPSHOT table (historical, append-only)
-- ============================================================================
CREATE TABLE CLAIM_SNAPSHOT (
    ID                  BIGINT          NOT NULL DEFAULT NEXT VALUE FOR SNAPSHOT_SEQ,
    VERSION             INTEGER         DEFAULT 0,
    CLAIM_ID            BIGINT          NOT NULL,
    SNAPSHOT_DATE       TIMESTAMP       NOT NULL,
    SNAPSHOT_REASON     VARCHAR(100),
    POLICY_NUMBER       VARCHAR(20),
    CLAIM_NUMBER        VARCHAR(20),
    STATUS              VARCHAR(20),
    CLAIM_TYPE          VARCHAR(30),
    ESTIMATED_LOSS      DECIMAL(14,2),
    APPROVED_AMOUNT     DECIMAL(14,2),
    ADJUSTER_CODE       VARCHAR(10),
    FRAUD_SCORE         INTEGER,
    FRAUD_RISK_LEVEL    VARCHAR(20),
    SERIALIZED_DATA     CLOB,
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_SNAPSHOT PRIMARY KEY (ID)
);

CREATE INDEX IDX_SNAPSHOT_CLAIM ON CLAIM_SNAPSHOT(CLAIM_ID);
CREATE INDEX IDX_SNAPSHOT_DATE ON CLAIM_SNAPSHOT(SNAPSHOT_DATE);

-- ============================================================================
-- POLICY_ENDORSEMENT table
-- ============================================================================
CREATE TABLE POLICY_ENDORSEMENT (
    ID                  BIGINT          NOT NULL DEFAULT NEXT VALUE FOR ENDORSEMENT_SEQ,
    VERSION             INTEGER         DEFAULT 0,
    POLICY_ID           BIGINT          NOT NULL,
    ENDORSEMENT_NUMBER  VARCHAR(20),
    ENDORSEMENT_TYPE    VARCHAR(50),
    EFFECTIVE_DATE      DATE,
    PREMIUM_ADJUSTMENT  DECIMAL(12,2),
    DESCRIPTION         VARCHAR(500),
    ACTIVE              BOOLEAN         DEFAULT TRUE,
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_ENDORSEMENT PRIMARY KEY (ID),
    CONSTRAINT FK_ENDORSEMENT_POLICY FOREIGN KEY (POLICY_ID) REFERENCES POLICY(ID)
);

CREATE INDEX IDX_ENDORSEMENT_POLICY ON POLICY_ENDORSEMENT(POLICY_ID);

-- ============================================================================
-- RECONCILIATION_REPORT table
-- Used by ClaimReconciliationTasklet to record payment discrepancies.
-- ============================================================================
CREATE TABLE RECONCILIATION_REPORT (
    ID                  BIGINT          IDENTITY PRIMARY KEY,
    CLAIM_ID            BIGINT          NOT NULL,
    CLAIM_NUMBER        VARCHAR(20)     NOT NULL,
    APPROVED_AMOUNT     DECIMAL(12,2),
    TOTAL_PAID          DECIMAL(12,2),
    DISCREPANCY         DECIMAL(12,2),
    REPORT_DATE         TIMESTAMP       NOT NULL,
    CONSTRAINT FK_RECON_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM(ID)
);

CREATE INDEX IDX_RECON_CLAIM ON RECONCILIATION_REPORT(CLAIM_ID);
CREATE INDEX IDX_RECON_DATE ON RECONCILIATION_REPORT(REPORT_DATE);

-- ============================================================================
-- ADJUSTER table
-- ============================================================================
CREATE TABLE ADJUSTER (
    ID                  BIGINT          NOT NULL DEFAULT NEXT VALUE FOR ADJUSTER_SEQ,
    VERSION             INTEGER         DEFAULT 0,
    ADJUSTER_CODE       VARCHAR(10)     NOT NULL,
    FIRST_NAME          VARCHAR(50)     NOT NULL,
    LAST_NAME           VARCHAR(50)     NOT NULL,
    EMAIL               VARCHAR(100),
    PHONE               VARCHAR(20),
    SPECIALIZATION      VARCHAR(50),
    ACTIVE              BOOLEAN         DEFAULT TRUE,
    MAX_CASELOAD        INTEGER         DEFAULT 50,
    CURRENT_CASELOAD    INTEGER         DEFAULT 0,
    CREATED_BY          VARCHAR(50),
    CREATED_DATE        TIMESTAMP,
    UPDATED_BY          VARCHAR(50),
    UPDATED_DATE        TIMESTAMP,
    CONSTRAINT PK_ADJUSTER PRIMARY KEY (ID),
    CONSTRAINT UK_ADJUSTER_CODE UNIQUE (ADJUSTER_CODE)
);

-- ============================================================================
-- Seed data for development
-- ============================================================================

-- Adjusters
INSERT INTO ADJUSTER (ID, ADJUSTER_CODE, FIRST_NAME, LAST_NAME, EMAIL, SPECIALIZATION, ACTIVE, MAX_CASELOAD, CURRENT_CASELOAD, CREATED_BY, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR ADJUSTER_SEQ, 'ADJ001', 'Robert', 'Mitchell', 'r.mitchell@greylegacy.com', 'AUTO', TRUE, 50, 3, 'SYSTEM', CURRENT_TIMESTAMP, 0);

INSERT INTO ADJUSTER (ID, ADJUSTER_CODE, FIRST_NAME, LAST_NAME, EMAIL, SPECIALIZATION, ACTIVE, MAX_CASELOAD, CURRENT_CASELOAD, CREATED_BY, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR ADJUSTER_SEQ, 'ADJ002', 'Sarah', 'Chen', 's.chen@greylegacy.com', 'HOME', TRUE, 40, 12, 'SYSTEM', CURRENT_TIMESTAMP, 0);

INSERT INTO ADJUSTER (ID, ADJUSTER_CODE, FIRST_NAME, LAST_NAME, EMAIL, SPECIALIZATION, ACTIVE, MAX_CASELOAD, CURRENT_CASELOAD, CREATED_BY, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR ADJUSTER_SEQ, 'ADJ003', 'Marcus', 'Williams', 'm.williams@greylegacy.com', 'COMMERCIAL', TRUE, 30, 28, 'SYSTEM', CURRENT_TIMESTAMP, 0);

INSERT INTO ADJUSTER (ID, ADJUSTER_CODE, FIRST_NAME, LAST_NAME, EMAIL, SPECIALIZATION, ACTIVE, MAX_CASELOAD, CURRENT_CASELOAD, CREATED_BY, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR ADJUSTER_SEQ, 'ADJ004', 'Elena', 'Rodriguez', 'e.rodriguez@greylegacy.com', 'MEDICAL', TRUE, 45, 5, 'SYSTEM', CURRENT_TIMESTAMP, 0);

-- Sample Policies
INSERT INTO POLICY (ID, POLICY_NUMBER, STATUS, POLICY_TYPE, HOLDER_FIRST_NAME, HOLDER_LAST_NAME, HOLDER_EMAIL, EFFECTIVE_DATE, EXPIRATION_DATE, PREMIUM_AMOUNT, COVERAGE_LIMIT, DEDUCTIBLE, AGENT_CODE, CREATED_BY, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR POLICY_SEQ, 'POL-2025-001', 'ACTIVE', 'AUTO', 'James', 'Peterson', 'j.peterson@email.com', '2025-01-01', '2026-01-01', 1200.00, 100000.00, 500.00, 'AGT01', 'SYSTEM', CURRENT_TIMESTAMP, 0);

INSERT INTO POLICY (ID, POLICY_NUMBER, STATUS, POLICY_TYPE, HOLDER_FIRST_NAME, HOLDER_LAST_NAME, HOLDER_EMAIL, EFFECTIVE_DATE, EXPIRATION_DATE, PREMIUM_AMOUNT, COVERAGE_LIMIT, DEDUCTIBLE, AGENT_CODE, CREATED_BY, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR POLICY_SEQ, 'POL-2025-002', 'ACTIVE', 'HOME', 'Maria', 'Garcia', 'm.garcia@email.com', '2025-03-15', '2026-03-15', 2400.00, 350000.00, 1000.00, 'AGT02', 'SYSTEM', CURRENT_TIMESTAMP, 0);

INSERT INTO POLICY (ID, POLICY_NUMBER, STATUS, POLICY_TYPE, HOLDER_FIRST_NAME, HOLDER_LAST_NAME, HOLDER_EMAIL, EFFECTIVE_DATE, EXPIRATION_DATE, PREMIUM_AMOUNT, COVERAGE_LIMIT, DEDUCTIBLE, AGENT_CODE, CREATED_BY, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR POLICY_SEQ, 'POL-2025-003', 'ACTIVE', 'COMMERCIAL', 'TechCorp', 'Industries', 'claims@techcorp.com', '2025-06-01', '2026-06-01', 8500.00, 1000000.00, 5000.00, 'AGT01', 'SYSTEM', CURRENT_TIMESTAMP, 0);

INSERT INTO POLICY (ID, POLICY_NUMBER, STATUS, POLICY_TYPE, HOLDER_FIRST_NAME, HOLDER_LAST_NAME, HOLDER_EMAIL, EFFECTIVE_DATE, EXPIRATION_DATE, PREMIUM_AMOUNT, COVERAGE_LIMIT, DEDUCTIBLE, AGENT_CODE, CREATED_BY, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR POLICY_SEQ, 'POL-2024-EXP', 'EXPIRED', 'AUTO', 'John', 'Doe', 'j.doe@email.com', '2024-01-01', '2025-01-01', 900.00, 50000.00, 500.00, 'AGT03', 'SYSTEM', CURRENT_TIMESTAMP, 0);
